### ISSUE TITLE
Allow customers to modify their DNS records

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#12]
Requirements:
- customers may not override WP-palvelu.fi core settings
  - @ and www records must always point to the site
- customers may add, edit and remove subdomains
- customers may add, edit and remove MX records
- customers may add, edit and remove TXT records other than those that are WP-palvelu.fi settings
- customers may add valid server names to SPF field, but not remove the WP-palvelu.fi settings

~~Due to secutiry reasons the UI should edit WP options of customer site. Our external tool will read the fields and use Gandi API. Customer site PHP cannot have direct access to Gandi API, that would constitute a security hole.~~ This part is not relevant anymore, as we have the direct API to our own backend now.

**Comment by ottok** [comment]
This is waiting or internal API to be available to the Seravo plugin.

**Comment by elguitar** [comment]
Forgot to mention here that the internal API is now implemented!

**Comment by elguitar** [comment]
Closing this, since editing is very much possible since bbd1e8f439f96c71f2decaa7fb262c0874f75c71.
