### ISSUE TITLE
Relabel "Technical contacts" to "Contacts" and require at least one email to be present

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#124]
As these contact emails may actually be used for other than technical purposes, we should relabel the field and move it away from the "Updates" page to a completely new context, e.g. a page for site plan details and contact information. Also, we should make it required in the UI for at least one contact email to be present.

**Comment by elguitar** [comment]
There are three subtasks to this issue:
1. Relabel Technical contacts to Contacts
1. Implement form validation that there is more than zero contact
1. Move the contact field away from Updates box

@Moppa5 You can focus on the first two. The third one should be done as a part of https://github.com/Seravo/seravo-plugin/issues/233 and/or https://github.com/Seravo/seravo-plugin/issues/98
