### ISSUE TITLE
Allow customers to edit their email aliases

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#13]
Once #12 is completed and the secure Gandi API tool is implemented, extend it to alow customers to edit their email aliases.

**Comment by ottok** [comment]
Status: The API has been implemented. Next step is to implement it on the Seravo Plugin dashboard side.

**Comment by elguitar** [comment]
@JoosuaKoskinen What's the status here? Is there a WIP branch somewhere?

**Comment by JoosuaKoskinen** [comment]
There's a PR now https://github.com/Seravo/seravo-plugin/pull/372
