### ISSUE TITLE
Sort the tools provided by Seravo-plugin into concise categories

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#142]
Currently Seravo's  tools take up 10 rows Tools-tab
![image](https://user-images.githubusercontent.com/16817737/42205752-f4b40b6c-7ead-11e8-81bd-05a8bcd6d21a.png)
I've come up with a suggestion to decrease the number of tabs to 3, making the plugin easier to use, decreasing clutter and combining similar functionalities together.
![image](https://user-images.githubusercontent.com/16817737/42206282-5744d3f0-7eaf-11e8-941a-4c2498d6d087.png)
_a sketch of what the end result might look like_

**Comment by mikkoaf** [comment]
I suggest that the categories could resemble the tasks that can be preformed and the information provided with the tools.
For example the layout could be

1. Data Usage or Content Management or similar

- Any backup-related features
- Any database-related features
- Cruft-file and -plugin features
- Image optimization

2. Maintenance or administrative tasks

- Any reports-related features
- Logs
- Updates and site status features
- Tests
- Data integrity

3. Developer tools

- Shadows-feature

**Comment by mikkoaf** [comment]
This is a duplicate of #98

**Comment by mikkoaf** [comment]
WordPress postbox elements usually are reserved for simple functionalities and showing information. Settings are traditionally shown as their own pages.

After discussing with @tlxo we came to the conclusion that Logs and Domains -pages should be left as their own submenu-pages as they do not translate to postboxes well. The Image optimization tool is such a small functionality which can be considered turning into a postbox, even though it is technically a setting.

**Comment by mikkoaf** [comment]
I've managed to reduce the menu to the following:
![image](https://user-images.githubusercontent.com/16817737/42678860-dfe3e184-8688-11e8-83a5-ce90c973747f.png)
"Päivitykset" and "Optimoi kuvia" are the next ones to be refactored to use AJAX and , after that this is pretty much a case of UX optimizing.

**Comment by l3ku** [comment]
Now that we have our own postboxes in the plugin instead of hard-coded pages, the tools can be easily swapped between different admin screens.

**Comment by ottok** [comment]
@nuuttitoivola @elguitar @JoosuaKoskinen This issue needs an status update

**Comment by nuuttitoivola** [comment]
The current status in the version `1.9.20` is as follows: 
![Screenshot from 2020-06-20 10-38-06](https://user-images.githubusercontent.com/26626224/85196340-4a78b880-b2e2-11ea-949e-6788fdc8ca4b.png)
The Seravo plugin part of the menu is `Site Status, Upkeep, Database, Backups, Security, Domains, Logs`.

I consider this issue as done. Resolved #142
