### ISSUE TITLE
Additional information on Domains-page should be shown in context

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#144]
Currently the Domains page opens additional information fields to the bottom of the page, which is convenient and neat when the list is quite short. These should be shown in context within the table.

![image](https://user-images.githubusercontent.com/16817737/42324895-3e34899a-806d-11e8-9751-a2f9c0e9c797.png)

Additional screenshots and UI mock-ups will be provided at a later time.

**Comment by ottok** [comment]
Done by @JoosuaKoskinen in https://github.com/Seravo/seravo-plugin/commit/d283fd138734d0c8d8e2bc99e84abb3d19b2238f. Closing issue.
