### ISSUE TITLE
Remove WordPress infoboxes from inside Seravo-plugin postboxes

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#145]
Currently WordPress prints it's information boxes on each site within WordPress. When this occurs on with pages with the new layout, the infoboxes are printed into a postbox, before the actual functionality.
![image](https://user-images.githubusercontent.com/16817737/42513403-8993f01a-845f-11e8-9df6-da53ea1797e3.png)

**Comment by l3ku** [comment]
This is most likely related to the HTML markup we use in our postbox pages. After a little bit of investigation, I realised that we always include
```
<div id="wpbody" role="main">
  <div id="wpbody-content" aria-label="Main content" tabindex="0">
    <div class="wrap">
```
on our postbox pages, but this is supposed to be added by WP itself from the WP core file `admin-header.php`. As a result, it is added two times in the page source:
![screen shot 2018-07-16 at 11 48 55](https://user-images.githubusercontent.com/24781811/42749978-43f11a18-88ee-11e8-80eb-8c03284fa261.png)

After changing removing the lines 
```
<div id="wpbody" role="main">
  <div id="wpbody-content" aria-label="Main content" tabindex="0">
    <div class="wrap">
```
from the beginning our postbox pages, the layout is correct:
![screen shot 2018-07-16 at 11 51 14](https://user-images.githubusercontent.com/24781811/42750085-94e8b5ca-88ee-11e8-9f85-9daa5e9740cb.png)
