### ISSUE TITLE
Make Updates-page fail gracefully when in development environment

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#148]
Updates page when it is working normally
![image](https://user-images.githubusercontent.com/16817737/42677746-65662230-8685-11e8-8cae-7a01b2a373ce.png)
Due to the nature how the Updates page is currently setup, it only returns the following in local development environment:
![image](https://user-images.githubusercontent.com/16817737/42677816-a4a7fe82-8685-11e8-98c3-3fdf4adf1dec.png)
This makes developing quite difficult due to the disruptive nature of the message and if such an event would occur in production, I would rather show postboxes with "Service temporarily unavailable" -message or such.

**Comment by l3ku** [comment]
Fixed in e521d2f. Next time, use GitHub's automation (Closes: xx) so issues don't have to be manually closed afterwards.
