### ISSUE TITLE
Cruft-file remover shows folders and the contained files as separate items

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#153]
This currently how cruft-files are searched, presented and removed can have unintended effects. 
![image](https://user-images.githubusercontent.com/16817737/43075167-8e025c94-8e88-11e8-9ecc-9dbe5e214541.png)
Selecting only the last cruft item on the list removes the whole folder with only a single prompt and on the UI only the last item is removed. This also makes estimating the actual used storage space difficult, as files inside folders that are listed are essentially twice - once as their own items and once included in the storage space used by the folder.

**Comment by l3ku** [comment]
Fixed in bead5f1. Next time, use GitHub's automation (Closes: xx) so issues don't have to be manually closed afterwards.
