### ISSUE TITLE
Show the user how much space can they save by optimizing image sizes

### ISSUE THREAD

**Issue by mikkoaf** [Seravo/seravo-plugin#155]
This issue can be solved by communicating with the user by writing suitable descriptions and estimating the amount of storage space that could be saved by optimizing images.

**Comment by Moppa5** [comment]
Personally I'm not sure how needed this feature would be individually. Perhaps if we implemented a feature that would show in general how much disk space can be saved with some actions or features in this case. This could be somehow integrated to cruft remover or diskspace analyzer. Nevertheless, this requires more plans before implementing.

**Comment by ottok** [comment]
This feature is not needed as new sites have image optimization on by default anyway. Also, spending a million CPU cycles to tell the user if the space saved is 15,5% or 20,1% is not that relevant to be accurate, we could just have a notification in the disk usage box stat says "turn on image optimization to save 15% of disk space". But that is probably overkill as the image optimization box is right under the disk usage box anyway.
