### ISSUE TITLE
Tests-tool postbox should have the same style and functionality as the other tools

### ISSUE THREAD

**Issue by nasusa** [Seravo/seravo-plugin#158]
In tests-tool
- postbox accordion does not work.
- postbox is 1/4 width of the screen, while everywhere else the postbox is at least 1/2 width.
- also, when hovering over postbox; cursor is `cursor: move`. I think it should be `cursor: pointer` (like everywhere else) because there is not (at least not yet) functionality to move the box.

![image](https://user-images.githubusercontent.com/15683849/43135896-b534d7f2-8f4f-11e8-9456-a2590c8e56d1.png)

**Comment by l3ku** [comment]
The tests tool was implemented as a Seravo postbox in 2e02ab, which solved these problems.
