### ISSUE TITLE
Show for developers more information about the database disk usage

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#163]
Examples regarding tracking down why wp_postmeta table is big:
* Show longest meta_value fields: `select meta_key, substr(meta_value, 1, 30) as meta_value_snip, length(meta_value) as meta_value_length  from wp_postmeta order by length(meta_value) desc limit 20;`
* Show cumulative size of meta_value per meta_key: `select meta_key, substr(meta_value, 1, 30) as meta_value_snip, length(meta_value) as meta_value_length, sum(length(meta_value)) as length_sum  from wp_postmeta group by meta_key order by length_sum desc limit 20;`
* Show what meta_key has most rows: `select substring(meta_key, 1, 12) as s, count(*) as c from wp_postmeta group by s order by c desc limit 20`

**Comment by Moppa5** [comment]
@ottok, Do you have any kind of wireframe on your mind? Should there for instance be some kind of charts used or just some raw data? @sjaks has been working with the disk and database usage charts so it might need some GUI designing on how to integrate these in a visually appealing way.

**Comment by ottok** [comment]
> @ottok, Do you have any kind of wireframe on your mind? Should there for instance be some kind of charts used or just some raw data? @sjaks has been working with the disk and database usage charts so it might need some GUI designing on how to integrate these in a visually appealing way.

No, I don't have not drafted any plans around visualizing this. I am
not even sure how much this can be visualized. Maybe just a simple
list of text but formatted as bullet points or something (to avoid a
plain <pre> text dump)?

**Comment by sjaks** [comment]
There are often multiple rows in the tables output by the example commands, for example (and there even are limiters).
If basic lists are used, they should be hidden by default under a toggle menu.

**Comment by sjaks** [comment]
There could be a really simple list like the following that would be behind a toggle element so that the numbers do not pop up and look confusing by default.
![Screenshot from 2020-07-24 09-02-02](https://user-images.githubusercontent.com/44066308/88364695-66adc080-cd8c-11ea-86fa-a33d6d6b11b6.png)

`wp-db-info` has many interesting outputs. We should list the ones that are parsed into wp-admin.

**Comment by sjaks** [comment]
Made a simple example:
![Screenshot from 2020-07-24 09-27-20](https://user-images.githubusercontent.com/44066308/88365844-fa34c080-cd8f-11ea-992d-c4928473c2f3.png)
![Screenshot from 2020-07-24 09-27-27](https://user-images.githubusercontent.com/44066308/88365851-fef97480-cd8f-11ea-95f6-9ff221b37102.png)

**Comment by Moppa5** [comment]
Seems nice @sjaks! The toggle box is also good for consistency since similar ones are used on Upkeep site too.

**Comment by sjaks** [comment]
In https://github.com/Seravo/seravo-plugin/pull/419, the queries in `wp-db-info` and the example queries in this issue have been *merged* and shown in wp-admin.
