### ISSUE TITLE
Add shortcode + function for easy credits link

### ISSUE THREAD

**Issue by onnimonni** [Seravo/seravo-plugin#17]
This would make it easier for our satisfied customers to give some credit back to us if they want to :).

Remember to translate this at least in Finnish / English.

FIN: Nopea ja turvallinen WordPress
ENG: Optimized WordPress Hosting

**Comment by l3ku** [comment]
Do we still need this feature in 2018?

**Comment by ottok** [comment]
No. Closing issue.
