### ISSUE TITLE
Nocache option for post edit screen OR geo aware cache

### ISSUE THREAD

**Issue by tlehtimaki** [Seravo/seravo-plugin#177]
It would be great to have an option on post edit screen to add nocache header/const/whatever works. Because sometimes there is pages you specifically want opt out from cache and it could be handy to have checkbox for that.

**Comment by ottok** [comment]
Thanks for the idea!

Can you supply a use case example or a user story so we can better design the feature to match a real need?

**Comment by tlehtimaki** [comment]
Case: We need some logic to be processed in backend with PHP eg. based on user IP, behavior in the site or other user related. Then we use this info to alter the rendered result for user. I acknowledge this could also be done with JS, but sometimes you don't have the opportunity to do that.

**Comment by ottok** [comment]
Can that PHP logic itself just emit `header("Cache-control: no-cache, no-store, no-validate;")`? If you have some logic already in PHP, should it not be able to control the caching then?

Is the user IP thing geo-IP related or some other IP checking?

**Comment by tlehtimaki** [comment]
The logic itself could do that too. The added benefit would be see this behaviour in the admin. Though I admit, that it might be too much for the average user but for administrator it might be very useful. (As would be many other info about the page/post too eg. errors generated by this page, load speed etc.)

You are correct about the IP address, I was mainly thinking about location suggestion based on geo-IP.

**Comment by ottok** [comment]
So if the caching is based on geo-IP, then actually what you want is not to disable caching, but to have a caching layer that has geo-zones? This is a feature we have had in our roadmap since June.

**Comment by tlehtimaki** [comment]
I did not think of it that way, but sounds like cool idea.

**Comment by ottok** [comment]
Geo aware cache development continues in another repo.
