### ISSUE TITLE
Undefined index when run via WP cli

### ISSUE THREAD

**Issue by ypcs** [Seravo/seravo-plugin#184]
Got following errors when ran commands using `wp` (-cli).
```
PHP Notice:  Undefined index: HTTP_HOST in /data/wordpress/htdocs/files/mu-plugins/seravo-plugin/lib/canonical-domain-and-https.php on line 32
Notice: Undefined index: HTTP_HOST in /data/wordpress/htdocs/files/mu-plugins/seravo-plugin/lib/canonical-domain-and-https.php on line 32
```

**Comment by ottok** [comment]
What version of seravo-plugin? Did you try `wp-seravo-plugin-update`?

**Comment by ypcs** [comment]
`Version: 1.9.2`

**Comment by l3ku** [comment]
The relevant line:
https://github.com/Seravo/seravo-plugin/blob/639f3ad7eb624601dd425df455872b0acfcce303/lib/canonical-domain-and-https.php#L32
As far as I'm concerned, there is nothing on this line that should cause that PHP notice...

**Comment by ypcs** [comment]
This happen when cron runs execute as well, see e.g. `rfc822msgid:20181125050158.81CC6144962C@fi-m2.seravo.com` (received by hostmaster), this includes some examples from 25th November.

**Comment by l3ku** [comment]
Can't find this in any recent hostmaster mails nor can replicate this manually. It seems that this is bug should even be possible to reproduce due to first checking the index`HTTP_HOST` with `isset()`.

**Comment by l3ku** [comment]
Could not find any indication of this problem still persisting. If someone is able to reproduce it, please add very verbose information about in which site and which context this occurred so it can be debugged.
