### ISSUE TITLE
Remove loading the nonexistent "shadows.css" file

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#186]
This is a very quick and easy fix, but I added it as a new issue for providing a low-treshold first production contribution. On the line
https://github.com/Seravo/seravo-plugin/blob/639f3ad7eb624601dd425df455872b0acfcce303/modules/shadows.php#L46
a file `shadows.css` is loaded, but no such file exists in the style directory, causing a 404 error:
![screen shot 2018-10-29 at 16 50 35](https://user-images.githubusercontent.com/24781811/47658224-48a53300-db9b-11e8-97e9-e638980ae582.png)

The line should be removed and possibly reintroduced, when there is a need to provide custom style the shadows page.

**Comment by JoosuaKoskinen** [comment]
The file `shadows.css` is now used and is loaded by intention. When to load it, must be controlled but that's unrelated to this issue.
