### ISSUE TITLE
RSS feed shows excerpts instead of full content

### ISSUE THREAD

**Issue by msaari** [Seravo/seravo-plugin#197]
Kirjavinkit.fi shows excerpts in the feeds, even though WordPress is set to show full posts. This changed with the Seravo plugin update to 1.9.3 (from 1.8.0, I think). In earlier versions, URL relativization loads the transient like this:

`if ( (isset($_SERVER['HTTP_PRAGMA']) && $_SERVER['HTTP_PRAGMA'] === 'no-cache') || false === ( $content = get_transient( $transient_key ) ) ) { `

while current version does it like this:

`$content = get_transient( $transient_key ); 
if ( ( isset($_SERVER['HTTP_PRAGMA'] ) && $_SERVER['HTTP_PRAGMA'] === 'no-cache' ) || false === ( $content ) ) { `

Not really sure how this changes the full post to an excerpt. Before the `get_transient()` call, `$content` has the full article, but the transient returns an excerpt. If I comment it out, the feed contains full posts again, full posts are saved to transients and the feed works.

This is how this works on Vagrant, can't really check on this in production, because transients are not in the database, so I can't see what's inside them (because I don't know the names of the transients). Wiping out all the transients didn't help, though.

**Comment by ottok** [comment]
Thanks for the report! We will look into this.
