### ISSUE TITLE
Domain zone edit should detect if zone isn't manageable

### ISSUE THREAD

**Issue by ypcs** [Seravo/seravo-plugin#203]
Plugin should perhaps tell explicitly why editing isn't possible. In this case, DNS isn't managed by Seravo, but plugin shows view/edit links for the zone anyways.

![screenshot from 2018-11-30 11-22-16](https://user-images.githubusercontent.com/97568/49280238-5566c080-f492-11e8-8970-c1a7c273e54d.png)

It would be preferred to tell the real status to the user, "DNS not managed by Seravo, see more details" with link to some help article. Also, if editing isn't possible, edit/view links should be hidden.

**Comment by elguitar** [comment]
Fixed via f2c34308af7e7b84f1fe978671c8ac851668ecd7. Closing
