### ISSUE TITLE
Make the shadow resetor UI more informative

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#207]
Currently, when pressing the "Reset shadow" button, no other indication of progress is shown except the disabling of the button:
 
![screen shot 2018-12-05 at 13 38 04](https://user-images.githubusercontent.com/24781811/49511151-04403d80-f893-11e8-87fc-d23c4aa14293.png)

At least for me, this is not a very informative indicator of the shadow resetting actually being in progress. Also, the success indication could also be more informative than just having "Success" displayed on the still disabled button:
![screen shot 2018-12-05 at 13 38 47](https://user-images.githubusercontent.com/24781811/49511218-36519f80-f893-11e8-85eb-03086da1ba46.png)

In case of errors, "Error" is displayed on the disabled button instead of "Success".

I don't have any proposed UI solution for this, so feel free to experiment.

**Comment by elguitar** [comment]
Closed via https://github.com/Seravo/seravo-plugin/commit/959083f9d47e63e4b732c5886eb8ad16f32368dd
