### ISSUE TITLE
Add the Staging instance switcher and purge cache to mobile.

### ISSUE THREAD

**Issue by VeetiYliHemmo** [Seravo/seravo-plugin#210]
In the current version the Staging instance switcher and the purge cache feature are not available on mobile devices:

![image](https://user-images.githubusercontent.com/42264016/49994251-a4801b80-ff91-11e8-84ec-e4c24827e829.png)

These are important features that should be accessible on mobile devices.

**Comment by ottok** [comment]
Good idea!
