### ISSUE TITLE
Unify and beautify cruft files screen

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#215]
Current Cruft files page looks like this:
![image](https://user-images.githubusercontent.com/668724/50492628-6d921700-0a21-11e9-8953-3a337c6d4112.png)

There are no 3 types of tables here:
- one plain table with trash bin icons in front of the row
- one table with black row dividers and trash bin icons in front of the row
- one table with select boxes in front of the row

This hurts my eye. All tables should have a unified look.

Also the UI uses JavaScript alert boxes. There should be some more WordPressish in-line feedback boxes. Also none of the messages should say that an action is irrevocable. If a backup has been run, then all of the files removed in this screen can be recovered within 30 days.

The text on this page shoud also very clearly motivate the site admin to clean up unnecessary files on 3 grounds:
- Extra files take up extra disk space
- Extra data (sql dumps in particular) might leak user data and passwords and is a big liability (GDPR if not otherwise)
- Extra PHP files can serve as an entry point for hackers, so all files that are unnecessary should be removed

**Comment by mikkoaf** [comment]
When unifying the tables, mobile usability should also taken into account.
![image](https://user-images.githubusercontent.com/16817737/50629570-ca239380-0f45-11e9-9863-f73aa68e1f41.png)

**Comment by mikkoaf** [comment]
The UI uses JavaScript alertboxes, because the action of modifying files on the server was considered something that requires the user's full attention. Using WordPress in-line feedback suits better situations where the action is not currently active, but requires attention.

Alertboxes have a place in WordPress. A similar-ish example from All-In-One WP Migration -plugin:
![image](https://user-images.githubusercontent.com/16817737/50678760-f18f6480-1008-11e9-9ae0-6d117c05846e.png)

**Comment by ottok** [comment]
Your screenshot shows a modal screen, not a JavaScript alert.

**Comment by nasusa** [comment]
![image](https://user-images.githubusercontent.com/15683849/53298428-a1799500-3836-11e9-9908-158273424610.png)

How about this? I like the possibility of selecting all files.

**Comment by ottok** [comment]
Nice and uniform! Red is good for deleting stuff.

**Comment by ottok** [comment]
@nasusa I which branch can I find the design screenshotted above?

**Comment by ottok** [comment]
@nasusa I which branch can I find the design screenshotted above?

**Comment by nasusa** [comment]
Oh yeah, sorry @ottok . I have been so busy with school and didn't notice any comments. Here: [https://github.com/Seravo/seravo-plugin/tree/dev-nasusa-cruft-files](/nasusa/seravo-plugin/tree/dev-nasusa-cruft-files)

Layout is still in progress. I'm trying to finish it this week.
