### ISSUE TITLE
Fix incorrect usage of Seravo Postboxes

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#228]
Example of places with incorrect usage:

## Mails
Incorrect call of `add_submenu_page()`, the function takes no 7th parameter and the 6th parameter should be `'Seravo\seravo_postboxes_page'`:
https://github.com/Seravo/seravo-plugin/blob/abf42101adbd0303b639caef3e3d5cd70ee7117e/modules/mails.php#L33-L35

Also the actual page content in `mails-page.php` should not define the postbox wrapper, only the content (div.inside) should be defined:
https://github.com/Seravo/seravo-plugin/blob/abf42101adbd0303b639caef3e3d5cd70ee7117e/lib/mails-page.php#L180-L191 are required

## Updates
Currently the updates module uses all postboxes as "side", however, "normal" should be primarily used. "side" is used only to force postboxes to the side, see https://codex.wordpress.org/Dashboard_Widgets_API#Advanced:_Adding_Widgets_onto_the_side for a description.

See e.g. `/modules/backups.php` for a reference of correct usage. Also, we have now added relevant docs to `/docs/README.md`. In case there is still some crucial information missing from the docs, here is a good opportunity to identify any missing information and expand the docs.

**Comment by ottok** [comment]
I assume this is a symptom of what Leo reported above:
![image](https://user-images.githubusercontent.com/668724/57223232-0d823180-700e-11e9-9d34-c2292e46d054.png)

**Comment by elguitar** [comment]
@cr0vy confirmed that the Updates page that @ottok mentioned is not an issue anymore. However, this #228 is still valid.

**Comment by ottok** [comment]
Closed via https://github.com/Seravo/seravo-plugin/commit/f1f50b7e76b2fa3fc56861380daa3c05a0630ec8
