### ISSUE TITLE
Extend contribution guidelines

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#231]
We have now documented briefly the Seravo Postboxes. Next step would be to extend the docs to cover how to code, test and make pull requests.

Using Github templates would make the experience smooth, see e.g.
![image](https://user-images.githubusercontent.com/668724/56427838-f0d3c300-62c5-11e9-9f44-ac464857c30d.png)

**Comment by l3ku** [comment]
We have now added some basic issue templates. The next steps would probably be to add a [CONTRIBUTING file](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) and a [pull request template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository).

**Comment by l3ku** [comment]
We have now added pull request / issue templates and a contributing file to this repo, so we have extended the contribution guidelines as the description of the issue says.
