### ISSUE TITLE
Clarify tests' message (tests via control panel)

### ISSUE THREAD

**Issue by Mardaukar** [Seravo/seravo-plugin#243]
The message after performing tests via control panel are misleading to the user. Even if the tests report failures, the message reads: "Testit suoritettu onnistuneesti ilman virheitä!"

Go to: WordPress control panel -> Työkalut -> Tests.
Press: "Suorita testit", under "Testit (uusi Codeception)".
After tests should read: "Testit suoritettu onnistuneesti ilman virheitä!"

![Screenshot from 2019-05-24 09-51-01](https://user-images.githubusercontent.com/50039402/58313352-06349380-7e16-11e9-85ca-f31249340ba1.png)

![Screenshot from 2019-05-24 09-49-52](https://user-images.githubusercontent.com/50039402/58313358-09c81a80-7e16-11e9-8aea-677e1dcf6758.png)

Additional context: Customer gave feedback on this.

**Comment by l3ku** [comment]
The AJAX functionality in https://github.com/Seravo/seravo-plugin/blob/master/lib/tests-ajax.php should in addition to the output probably also return the command exit code, and fail if it is nonzero. Currently the mechanism checks for some string present in the output at https://github.com/Seravo/seravo-plugin/blob/2d7649bb16de2ba6b61d64d69a97ed70ba8e0316/js/tests.js#L91, which is certainly not a good design.

**Comment by ottok** [comment]
Labelled this as priority since the feedback to the user is simply "Testit suoritettu onnistuneesti ilman virheitä!" by default (before they open the box with more info) so this is quite a grave functionality problem.

**Comment by mvierma** [comment]
Changing the checked string from https://github.com/Seravo/seravo-plugin/blob/2d7649bb16de2ba6b61d64d69a97ed70ba8e0316/js/tests.js#L91 to https://github.com/Seravo/seravo-plugin/blob/9ade94ac6e84638590a7eee7a304b3fb987eba37/js/tests.js#L17 fixes the display so it now shows if there are any failures in the tests. 
![image](https://user-images.githubusercontent.com/26429376/60811050-25ee0400-a197-11e9-9ad4-b4981be73b93.png)

This could be used as a quick fix before a more thorough update to the program logic.

**Comment by l3ku** [comment]
Can we assume that the output always contains the string "Failures"? What if "Failures" is somewhere else in the logging output of the customer's custom tests? 

I think that it would be better to fix this well once for all in the AJAX code running the test and returning the result to the client JavaScript. Assuming that it uses PHP `exec()` like most of the tools do, the `return_var` parameter of PHP `exec()` (https://www.php.net/manual/en/function.exec.php) could be used to return the success of the test.
