### ISSUE TITLE
Minor fixes before 1.9.9 release

### ISSUE THREAD

**Issue by mvierma** [Seravo/seravo-plugin#245]
- [x] cruft remover: falsely suggests removal of parent theme
- [x] cruft remover: exclude node_modules
- [x] tests: remove old rspec test
- [x] database: add line break to search and replace box's to and from fields
![image](https://user-images.githubusercontent.com/26429376/58943541-9e246c80-8788-11e9-9044-6c77c5f10539.png)
- [x] reports: fix undefined index
![image](https://user-images.githubusercontent.com/42264063/58948281-6cb09e80-8792-11e9-95ea-6b9aa27d3385.png)
- [x] updates: fix undefined index
![image](https://user-images.githubusercontent.com/42264063/58948359-9bc71000-8792-11e9-9a06-1cf65d764e56.png)

**Comment by ottok** [comment]
PHP version change does not seem to complete?
![image](https://user-images.githubusercontent.com/668724/59087705-1ff1d280-890e-11e9-90f4-15ac2f0714b8.png)

**Comment by elguitar** [comment]
@ottok noticed that the Publish button is not working on domains_page. This is probably because it doesn't use the AJAX system yet.
This should be fixed before 1.9.9 too. 

@JoosuaKoskinen and I will sort this out :)

**Comment by JoosuaKoskinen** [comment]
These issues has been fixed in the commits referencing this and 1.9.9 has been published.
