### ISSUE TITLE
Embed Helpy to WordPress dashboard

### ISSUE THREAD

**Issue by nuuttitoivola** [Seravo/seravo-plugin#246]
**Is your feature request related to a problem? Please describe.**
Seravo WordPress users should be able to use Seravo documentation directly from the WordPress admin.

**Describe the solution you'd like**
We want to embed Helpy Carin bot to the Seravo Plugin pages or WordPress dashboard.

**Describe alternatives you've considered**
Is it possible to embed ticketing  form direclty or link to it on help.seravo.com to the admin panel instead?

**Additional context**
Carin bot could help bringing Seravo documentation closer to the users.
- https://helpy.io/support-bot/

**Comment by JoosuaKoskinen** [comment]
@Mardaukar
I customized loading it a bit and it seems to work fine. I'm not exactly sure what's supposed to happen but I got a yellow head at bottom right corner and clicking it opened some kind of chatbox.

I used the following JavaScript:
```
jQuery(document).ready(function() {
  $script('//helpy.io/js/bot.v5.js', function() {
    $ = jQuery.noConflict();
    var Helpy = Helpy || {};
    Helpy.domain = '//help.seravo.com';
    Helpy.botIcon = ''; 
    Helpy.botBackground = '#f0b40e';
    Helpy.email_address = ''; 
    Helpy.customer_name = '';
    Helpy.initBot('d02VpXBADWPR31G8kQMjK8waxEvO4r'); 
  });
});
```

And I loaded the helpybot.js in PHP:
```
wp_register_script('helpybot', 'https://helpy.io/js/helpybot.js');
wp_enqueue_script('helpybot');
```

![image](https://user-images.githubusercontent.com/42264063/60262393-b9e1e500-98e6-11e9-9d67-b39a87ff37a3.png)

**Comment by nuuttitoivola** [comment]
WIP in branch https://github.com/Seravo/seravo-plugin/commits/dev-markus

**Comment by nuuttitoivola** [comment]
This issue is obsolete as we're going to start using Help Scout that can have these kind of integrations done more easily, for example via [Help Scout Beacon](https://www.helpscout.com/live-chat/).
