### ISSUE TITLE
Unable to reliably link to update.log 

### ISSUE THREAD

**Issue by mvierma** [Seravo/seravo-plugin#250]
In reference to issue #73. Currently it's not possible to reliably link to update.log on the Logs page, as the update.log -file may not exist depending on when the last site update was ran.
![image](https://user-images.githubusercontent.com/26429376/59425213-179e0980-8dde-11e9-9df7-8fa95f5da58a.png)
Currently Logs page fetches logs based strictly on the .log extension and doesn't show updates at all if no update.log is present.
![image](https://user-images.githubusercontent.com/26429376/59425298-45834e00-8dde-11e9-8ca7-3a061e6013ee.png)
After creating an empty update.log, the log shows up and is linkable for the notification about updates.

**Comment by ottok** [comment]
Would you like to code something that fetches the contents of the previous (rotated) update.log (and in general any log) if it is missing?

**Comment by mvierma** [comment]
Sure, I'll see what I come up with. Should the contents be printed onto to the reports page somewhere or in a new window perhaps?

**Comment by mvierma** [comment]
Logs page now checks for existence of all log types and fetches previous rotated log if any is missing and this issue is no longer valid.

**Comment by ottok** [comment]
What do you mean by "now"? Since which commit on master?

**Comment by mvierma** [comment]
The issue is fixed in commit b10102f but it is not yet merged to master. Reopening the issue now.

**Comment by ottok** [comment]
@mvierma Change commit subject from "Add fetching of rotated logs if any .log file is missing" to "Add fetching of rotated logs if any .log file is missing (Closes: 250)" and then you won't have to manually update any issue texts or close them.

By the way, the commit above has merge artifacts. Search for `======` and you will see.

**Comment by ottok** [comment]
Closed via b10102fb9c3bc236627f5351e2d95bded127dbc8
