### ISSUE TITLE
Notice: Undefined index: HTTP_REFERER

### ISSUE THREAD

**Issue by TeemuSuoranta** [Seravo/seravo-plugin#252]
When /wp-admin/ is opened in new tab when logged in, the HTTP_REFERER is not set and should be checked before referenced.

Full notice:
```
Notice: Undefined index: HTTP_REFERER in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/check-php-version.php on line 30
```

This can be simply checked by:
```
if (isset($_SERVER['HTTP_REFERER']) && strpos($_SERVER['HTTP_REFERER'], 'wp-login.php') === false) {
```

**Comment by ottok** [comment]
What version are you running? Did you try `wp-seravo-plugin-update` ?

**Comment by TeemuSuoranta** [comment]
It's the `1.9.9` which is the newest release. The buggy code is in https://github.com/Seravo/seravo-plugin/blob/master/modules/check-php-version.php#L30

**Comment by TeemuSuoranta** [comment]
PHP version is 7.2 in case that handling `$_SERVER['HTTP_REFERER']` has somehow changed in `7.3`

**Comment by JoosuaKoskinen** [comment]
This was fixed in https://github.com/Seravo/seravo-plugin/pull/253.
