### ISSUE TITLE
Cruft remover lists themes for deletion even if they're being used in Networks

### ISSUE THREAD

**Issue by nuuttitoivola** [Seravo/seravo-plugin#254]
**Is your feature request related to a problem? Please describe.**
The cruft remover makes it too easy to accidentally delete the themes of subsites even if they are being used at the time.

**Describe the solution you'd like**
Built in warning or work flow that prevent users making mistakes as easy as currently.  

**Describe alternatives you've considered**
Perhaps it would be possible to hide all themes/plugins that are in use on subsites, as they should not to be considered cruft.

**Comment by ottok** [comment]
There is already Network specific checks, e.g. https://github.com/Seravo/seravo-plugin/blob/master/seravo-plugin.php#L209-L214

That was implemented by @elguitar in https://github.com/Seravo/seravo-plugin/commit/8d33450d2f3cff52fe78730125723ea6327799ec

Further improvements require more specific descriptions of problems and specific fixes for them.

The title of this issue could thus be e.g. "Cruft remover does not correctly detect which themes and plugins are used in a Network".

**Comment by nuuttitoivola** [comment]
That is true, I updated the issue.
