### ISSUE TITLE
Provide UI to update the Seravo Plugin

### ISSUE THREAD

**Issue by cr0vy** [Seravo/seravo-plugin#255]
Currently Seravo plugin does not include any other updating method than cli `wp-seravo-plugin-update`. I'm working with Seravo Plugin updater, which will be found from updates page.

To-Do:
- [x] Add postbox with basic functions
- [ ] Add 'development version' function

Currently work in progress:
![image](https://user-images.githubusercontent.com/43742796/60016886-21eabe00-9690-11e9-928f-7fd2616e5dcc.png)

![image](https://user-images.githubusercontent.com/43742796/60016754-b6085580-968f-11e9-940d-096cdce5b239.png)

**Comment by ottok** [comment]
Please in the future make some rough plans first, and only then proceed with the implementation. It is important to get feedback on ideas and plans before they are done so one does not put effort on stuff that eventually is not needed.

In this case for example I think that we should not provide a UI to update to the dev version. That feature is really not for the target audience of the UI. It might just confuse them..

For the regular version upgrade it should state something along the lines "Seravo automatically updates you site and the Seravo Plugin as well. If you want to immediately update to the latest Seravo Plugin version, you can do it here."

**Comment by ottok** [comment]
Thanks for the issue! It's is a very good one, with clear substeps marked and UI mockups attached. :+1:

**Comment by ottok** [comment]
Where is the PR to close this? The code has been ready on the branch for two weeks already, hasn't it?
