### ISSUE TITLE
Replace current cache check Seravo postbox with output of wp-check-http-cache

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#281]
Since we have now rolled out `wp-check-http-cache` we should use it to show the cache status post box contents.

**Comment by JoosuaKoskinen** [comment]
Related to https://github.com/Seravo/seravo-plugin/issues/72

**Comment by JoosuaKoskinen** [comment]
Should wp-check-http-cache replace the whole postbox? It shows way less data than the current one. Maybe it should only replace the curl section.

```
joosuakoskinen@joosuakoskinen_bd3ab9:~$ wp-check-http-cache
----------------------------------------
Seravo HTTP cache checker
----------------------------------------
Testing https://alidomain-2.fi-s.seravo.com/...
Request 1: MISS
Request 2: HIT
Request 3: HIT
----------------------------------------
SUCCESS: HTTP cache works for https://alidomain-2.fi-s.seravo.com/.
----------------------------------------
You can also test this yourself by running:
  curl -IL https://alidomain-2.fi-s.seravo.com/
```

**Comment by JoosuaKoskinen** [comment]
This will be bundled with https://github.com/Seravo/seravo-plugin/issues/72.

**Comment by JoosuaKoskinen** [comment]
Closing, '`wp-check-http-cache`' used instead of cURL since https://github.com/Seravo/seravo-plugin/pull/300.
