### ISSUE TITLE
PHP warning: Cannot modify header information

### ISSUE THREAD

**Issue by cr0vy** [Seravo/seravo-plugin#284]
**Describe the bug**
On some sites php-error.log get a new entry on regular intervals, which is `PHP Warning: Cannot modify header information - headers already sent in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/canonical-domain-and-https.php on line 38`. This happens only URL with wp-cron.php.

**To Reproduce**
1. Go to site CLI on SSH
2. Run `tail -fn 0 /data/log/php-error.log`
3. Run in another terminal `curl -ILs http://example.com/wp-cron.php` or `curl -ILs example.com/wp-cron.php`
4. Check php-error.log entry

**Expected behavior**
Nothing should happen in /data/log/php-error.log

**Screenshots**
http:
![cannot_modify_header_information](https://user-images.githubusercontent.com/43742796/65668536-91cf6280-e04a-11e9-972f-fe0388069536.png)

https:
![https-curl](https://user-images.githubusercontent.com/43742796/65668549-972cad00-e04a-11e9-82a2-12868995d835.png)

**Comment by ottok** [comment]
Is there a `?>` in some file somewhere maybe? That will emit a newline.

The PHP files should not emit anything before WP actually starts to print out the real page.

**Comment by ottok** [comment]
To recap: this is not a problem in `canonical-domain-and-https.php`. That is just the first thing to emit headers. The problem is somewhere else that emits stuff before that.

I came across a similar situation:
```
$ wp option get siteurl

https://<site>.fi-p.seravo.com
$ 
```

The correct output should be:
```
$ wp option get siteurl
https://<site>.fi-p.seravo.com
$ 
```

So there is somewhere an extra newline emitted.

I found the problem here:
```
gp-child$ head functions.php 

<?php
// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) exit;
```

So the newline was at the beginning for the theme functions.php

**Comment by cr0vy** [comment]
I tested a few commit checkout to find the first commit to produce this warning.

Commit 2e4b4b1 (Bump version to 1.8.0) -> Ok
Commit 2eb11f8 (Bump version to 1.9.0) -> PHP Warning

Commit d6316fa (Remove function isPublic() as it does not seem to be used anywhere) -> Ok
Commit 64173bc (Enforce usage of https if siteurl and home has it set) -> The first commit with this PHP Warning

**Comment by JoosuaKoskinen** [comment]
Couldn't reproduce the warning in commit https://github.com/Seravo/seravo-plugin/commit/64173bcb5ef0a2bc5f830f9e84e5b21143d6c083, Was cache cleared after each test? The result seems odd.

**Comment by ottok** [comment]
@JoosuaKoskinen I think this only happens on certain sites that have some cron job that runs often or something. On sites where this happens the error can be triggered with `curl -IL http://example.com/wp-cron.php` (note insecure *http*).

Maybe the cron thing runs before mu-plugins code? Maybe the Seravo Plugin should check if `DOING_CRON` is defined and if so, not emit any redirects?

**Comment by cr0vy** [comment]
I may be found the reason for this "PHP Warning: Cannot modify header information". After a call of wp-cron.php, wp-cron.php trying to call fastcgi_finish_request() in lines 22-24. This leading to the situation, where headers send happening before Seravo Plugin loading. This only happens if the PHP version is at least 7.0.13.

**Comment by ottok** [comment]
Since we can't do anything about wp-cron.php in core right now besides file a bug report upstream, Seravo Plugin should check if DOING_CRON is defined and if so, not emit any redirects.
