### ISSUE TITLE
Views unaligned

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#287]
The layout is misaligned in two ways here: the margins don't align and the user experience is not aligned.

![image](https://user-images.githubusercontent.com/668724/66569416-36d25b00-eb74-11e9-886c-0d8ab998bf85.png)

We basically have two lists here. Couldn't they have the exact same layout, would that make sense?

**Comment by ottok** [comment]
This is not a complete UI design, I just did a quick mockup to illustrate the need:
![image](https://user-images.githubusercontent.com/668724/66804219-92ad3300-ef2a-11e9-9ea1-b66979a02fbf.png)

**Comment by JoosuaKoskinen** [comment]
@cr0vy do you still have some fix coming to this? My email postbox still seems to have 50% width. I don't want to have any conflicts with https://github.com/Seravo/seravo-plugin/issues/13.
