### ISSUE TITLE
Shadows box not user friendly

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#288]
The new shadows box is not very user friendly. When opened by default it looks like this:
![image](https://user-images.githubusercontent.com/668724/66569530-700acb00-eb74-11e9-8c43-75619289fe6b.png)

- untranslated text
- no list of shadows visible
- empty placeholders with no value visible even though a shadow does exits

When opened it looks also unfriendly:
![image](https://user-images.githubusercontent.com/668724/66569589-8ca70300-eb74-11e9-8819-192f6998f911.png)

Why do we have a drop-down here, would not a list be much better?

When opened it looks very complex:
![image](https://user-images.githubusercontent.com/668724/66569638-a5171d80-eb74-11e9-9327-30dfe92d94b9.png)

Compare this to the old shadows list, which was clear and there was a simple button to reset the shadow (the nr 1 feature users actually want to find and use):
https://seravo.com/docs/images/shadows-list.png

I opened this as a feature request, since this needs some designer to do the UI work.

**Comment by JoosuaKoskinen** [comment]
Related to https://github.com/Seravo/seravo-plugin/issues/277. I agree, it's clearly not the best design. The narrow postbox makes it difficult to fit a lot of information.

Note that the new design should be ready for `wp-shadow-pull` in addition of reset.

**Comment by ottok** [comment]
@nuuttitoivola @elguitar @JoosuaKoskinen This issue needs an status update perhaps? Also this seems to be a duplicate of #277 to a large part.
