### ISSUE TITLE
Shadow banners need some UX design

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#289]
Our current shadow banners need some UI design:
![image](https://user-images.githubusercontent.com/668724/66569839-0b03a500-eb75-11e9-8509-f98a33f4bca5.png)

What does the 'STAGING' actually tell the user? And the comment in the parenthesis does not add much value. We should have some UX design here to get this a smooth experience.

The same `NAME (comment)` pattern is in the warning banner:
![image](https://user-images.githubusercontent.com/668724/66569939-3be3da00-eb75-11e9-814c-0ea3f6a67681.png)

**Comment by JoosuaKoskinen** [comment]
Now that `WP_ENV_COMMENT` is fixed, I think we could use just that. I don't see how the comment doesn't add much value. It's often more informative than "Testivarjo".

The comment is usually "Staging" or one requested by the customer. I agree that it could be improved, "STAGING (Staging)" is not useful for the user.
