### ISSUE TITLE
Whitelist Jetpack IP addresses from XML-RPC blocker

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#297]
Most sites don't have any valid uses for XML-RPC anymore. Most sites use WP-JSON API.

However, Jetpack does use XML-RPC still. Our XML-RPC block should whitelist the Jetpack IP addresses. See `class Security_Restrictions`.

**Comment by ypcs** [comment]
Somewhat related upstream (Jetpack) issue about Automattic IP address ranges, https://github.com/Automattic/jetpack/issues/1719

**Comment by JoosuaKoskinen** [comment]
Here's a list of Jetpack IPv4 ranges I found:
https://jetpack.com/ips-v4.txt
https://jetpack.com/ips-v4.json

**Comment by ottok** [comment]
Right now I am not aware of anything else that should be whitelisted, so I think we could put these IPs directly in the Seravo Plugin for now instead of making any other more elaborate whitelisting list automation as discussed elsewhere.
