### ISSUE TITLE
The log scrolling feature not working right with log files of >50 lines

### ISSUE THREAD

**Issue by cr0vy** [Seravo/seravo-plugin#298]
**Describe the bug**
The log scrolling feature loads more lines from the file even if it's already on the first line of the file. This happens with log files that contain more lines than 50. 

**To Reproduce**
1. Go to logs page
2. Choose log that contains more than 50 lines (example: wp-php-compatibility.log)
3. Scroll up

**Expected behavior**
The log scrolling feature should stop at line 1, but it will reload again the same lines and adds those lines to the log viewer.

**Screenshots**
![logs_scrolling](https://user-images.githubusercontent.com/43742796/68667996-e9208800-054f-11ea-842d-34486f22a52b.gif)

**Additional context**
Tested with `for i in {1..75}; do echo "Line $i" >> /data/log/php-error.log; done` and the log scrolling feature works right, but outputs from scripts doesn't.

**Comment by ottok** [comment]
Install an older version of the plugin to find out in which version this still worked. Once you know when it worked, then you can look at the commits in between to find out which commit broke it.
