### ISSUE TITLE
Baseline test status not parsed from the latest logs

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/seravo-plugin#307]
**Describe the bug**
Upkeep page has a sections which shows the current status of pre-update tests. The oneliner `zgrep -h -A 1 "Running initial tests in production" /data/log/update.log* | tail -n 1 | cut -d " " -f 4-8` used to get the status, doesn't always use the latest log file (update.log) and the result might be incorrect.

**Expected behavior**
Log files should be parsed from latest to the oldest. So update.log first, update.log-xxxxxxxx then and update.log-*.gz last.

**Comment by ottok** [comment]
This was fixed in https://github.com/Seravo/seravo-plugin/pull/309, right @JoosuaKoskinen ?

**Comment by JoosuaKoskinen** [comment]
It was, yes
