### ISSUE TITLE
Cruft remover would check content also in home directory

### ISSUE THREAD

**Issue by simoke** [Seravo/seravo-plugin#308]
Currently the Cruft remover checks known files and directories under /data/wordpress/htdocs directory, but in many cases, customers also saves data (eg. SQL dumps) under home directory, and there are plenty of such data at the moment.

It would be good improvement to check also the home directory, and perhaps from another paths.

**Comment by JoosuaKoskinen** [comment]
Here's some I've seen that could be removed:
~/*backup*
~/core
~/*.bak
~/.sql
~/*palautus*
~/*before*
~/<sitename>_<yyyymmdd>
