### ISSUE TITLE
Add handling of 504 AJAX-responses

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/seravo-plugin#315]
Some AJAX-calls are quite likely to take over the timeout limit. Seravo Plugin should detect when so happens and instruct the user how to do the same with SSH.

Users might think (and have thought) there's something broken with their site or Seravo Plugin when the spinner keeps running infinitely.

One of calls that may do this is the wp-php-compatibility-check in php version changer.

**Comment by JoosuaKoskinen** [comment]
Example: https://github.com/Seravo/seravo-plugin/issues/187

**Comment by Wiljami** [comment]
Adding a .fail to the jquery posts ought to solve this issue. I created such to the upkeep page regarding to compatibility check in #423.

What other ajax calls are there in seravo-plugin that would also require this?

**Comment by elguitar** [comment]
@Wiljami is there still something to do in this issue or can we close this?

**Comment by Wiljami** [comment]
I think it's solved the best it could be. It informs the user if the response takes too long.

**Comment by elguitar** [comment]
Closing in favor of #465
