### ISSUE TITLE
Allow users to select PHP 7.4

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#318]
We have rolled out PHP 7.4 in production late last year and it is now available to pretty much all customers. Please update this screen to offer PHP 7.4 as an option:
![image](https://user-images.githubusercontent.com/668724/73049200-7b180b80-3e84-11ea-837e-b2dc2846473a.png)

Please also add a screenshot of this page to https://help.seravo.com/article/41-set-your-site-to-use-newest-php-version so that customers know that the command line is not the only way to update PHP version.

**Comment by JoosuaKoskinen** [comment]
This enhancement was added in https://github.com/Seravo/seravo-plugin/commit/22ad5c8f5ec65783565573b605bf259cc344c4c5. A draft of the docs change is also waiting to be published.
