### ISSUE TITLE
"Weak password" checkbox still visible and functional in lost-password screen

### ISSUE THREAD

**Issue by tnottu** [Seravo/seravo-plugin#322]
**Describe the bug**
Seravo-plugin disables the "Enable using weak password" checkbox in most places, but it is still visible and functional in the password-reset screen. JS-code disables the form Submit button, but toggling the checkbox enables the button again.

Seems that at the time of the [earlier fix](https://github.com/Seravo/seravo-plugin/issues/76) the checkbox didn't exist in the password-reset screen.

**To Reproduce**
1. Go to `/wp-login.php?action=lostpassword` on any site
2. Start password reset process for your user account
3. Check your mail, open the password reset link
4. Type a weak password and notice that the submit button is disabled.
5. Click on the "Vahvista heikon salasanan käyttö" (or whatever it in English) and notice that submit button is enabled again. This is a problem.
6. Change your password, keeping it still weak. Notice that the Submit button is disabled again.
7. Toggle the checkbox off and on again. Notice that submit button is enabled again. This is a problem.

**Expected behavior**
The weak password checkbox should not be functional, or even visible/existing.

**Screenshots**
![Screenshot 2020-02-06 at 16 19 32](https://user-images.githubusercontent.com/4559075/73946227-408b8580-48fe-11ea-95c6-862cd3113771.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 79.0.3945.130

**Additional context**
--
WordPress v5.3.2
Seravo plugin v1.9.15

**Comment by ottok** [comment]
Thanks for a great bug report!

@JoosuaKoskinen could look into this in the following weeks.
