### ISSUE TITLE
Shadow banner missing with some themes

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/seravo-plugin#325]
Some themes only use `get_footer` function instead of `wp_footer`. Seravo Plugin shadow banner only has a hook for `wp_footer` so the banner is not visible with `get_footer`. Missing banner caused a customer to complain.

Is not calling `wp_footer` in theme an acceptable thing to do? If so, should we replace `wp_footer` hook with `get_footer` or use them both somehow?

**Comment by JoosuaKoskinen** [comment]
After some research it seems that calling `wp_footer` is very recommended and I don't think we need to add support for not calling it. A customer with this issue has fixed their theme and we should recommend doing so in similar cases.

Closing this issue for now.

**Comment by ottok** [comment]
Please document this somewhere. For example in the Seravo Plugin readme and/or seravo.com/docs page about shadows.

FYI also @nuuttitoivola.
