### ISSUE TITLE
Wrong link in PHP update notification

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#333]
**Describe the bug**
I went to my page and saw a notification which kindly stated that I should consider upgrading PHP to 7.3. I clicked the link, but ended up on a page, which said that I have no permissions for the page.
**To Reproduce**
1. Make the PHP notification appear
1. Click the link

**Expected behavior**
The page, where I can update the PHP version should open.

**Screenshots**
![Screenshot_20200226_145750](https://user-images.githubusercontent.com/16290563/75346952-6b874a80-58a8-11ea-9b96-43525712c428.png)

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Browser Firefox
 - Version 73

**Additional context**
I believe that the link should be updated:
```
[~/seravo/seravo-plugin]: ag updates_page
modules/check-php-version.php
57:        __('PHP %s is available but not used on this site. Developers might want to <a href="tools.php?page=updates_page">upgrade the latest PHP version</a> for faster performance and new features. Read more about <a target="_blank" href="https://help.seravo.com/en/knowledgebase/13/docs/107-set-your-site-to-use-newest-php-version">PHP version upgrades</a>.', 'seravo'),

languages/seravo.pot
246:msgid "PHP %s is available but not used on this site. Developers might want to <a href=\"tools.php?page=updates_page\">upgrade the latest PHP version</a> for faster performance and new features. Read more about <a target=\"_blank\" href=\"https://help.seravo.com/en/knowledgebase/13/docs/107-set-your-site-to-use-newest-php-version\">PHP version upgrades</a>."

languages/seravo-fi.po
282:"href=\"tools.php?page=updates_page\">upgrade the latest PHP version</a> for "
288:"todennäköisesti <a href=\"tools.php?page=updates_page\">päivittää uusimpaan</"
```

**Comment by JoosuaKoskinen** [comment]
I've an empty notice. I assume that's supposed to be the PHP upgrade notice.

![Screenshot from 2020-02-27 10-55-50](https://user-images.githubusercontent.com/42264063/75427787-cf188300-594f-11ea-9fdb-4faac9ee306a.png)

**Comment by JoosuaKoskinen** [comment]
Fixed in https://github.com/Seravo/seravo-plugin/commit/a74411754e25e06b0abdacd80a9f7f56999319a6. Still needs to be fixed in translations.

**Comment by JoosuaKoskinen** [comment]
Translations fixed in https://github.com/Seravo/seravo-plugin/commit/048b66cfb92afde685c920291a22f094fe5d2cb8.
