### ISSUE TITLE
PHP compatibility error

### ISSUE THREAD

**Issue by sulavalehto** [Seravo/seravo-plugin#336]
When PHP version has been successfully changed and .log shows no errors, 
finds compatibility scanning 9 errors nevertheless.

Most likely to be the same error as issues handled below. 

#271 
#276 

![php-onnistuneesti-vaihdettu](https://user-images.githubusercontent.com/61628120/76082394-f3a9d600-5fb3-11ea-82a9-b4523b8e303c.png)
![php-log-tyhjä](https://user-images.githubusercontent.com/61628120/76082400-f86e8a00-5fb3-11ea-94a8-56c43d073948.png)
![php-yhteensopivuustarkistus-herjaus](https://user-images.githubusercontent.com/61628120/76082407-fad0e400-5fb3-11ea-86cf-dd88524f940c.png)

**Comment by JoosuaKoskinen** [comment]
The `php-error.log` isn't necessarily supposed to have anything in it. The "9 virhettä" should be in `wp-php-compatibility.log` which the "yhteentoimivuustarkistuksen tulokset" link will take you to. Can you check if you can find the errors in there?

The fact that there's PHP compatibility errors doesn't mean that the PHP version can't be changed or errors will be thrown. Often a lot of them are false positives. Nevertheless, the user is instructed to keep an eye on the `php-error.log`, in case something gets printed there (last paragraph in the first screenshot).

**Comment by sulavalehto** [comment]
The `php-error.log` is empty and as you said `wp-php-compability.log` also shows nothing regarding this issue and there is not a single track or source for the root of "9 virhettä". False positive seems to be the deal here in my understanding.

**Comment by sulavalehto** [comment]
The `php-error.log` is empty and as mentioned `wp-php-compability.log` is also showing nothing regarding this issue and there is not a single track or source for the root of "9 virhettä". False positive seems to be the deal here in my understanding.

**Comment by JoosuaKoskinen** [comment]
Everything seems to work as expected, closing this.
