### ISSUE TITLE
Improve UI for postbox content

### ISSUE THREAD

**Issue by pekkakortelainen** [Seravo/seravo-plugin#337]
Security and Database pages have issues with postbox content fitting well inside their respective containers. Version in use: 1.9.16 development (installed with wp-seravo-plugin-update --dev).

To reproduce:
- adjust the width of your browser window
- adjust your browser window zoom level

Security - Trash files
![seravo-plugin-trash-files-snap](https://user-images.githubusercontent.com/61181862/76079617-acb8e200-5fad-11ea-9fcc-bbae749ef02f.png)

Database - Search and replace results
![seravo-plugin-search-replace-results-snap](https://user-images.githubusercontent.com/61181862/76079925-72037980-5fae-11ea-8364-27457dbcb8f1.png)

**Comment by JoosuaKoskinen** [comment]
I assume you mean `1.9.16` as `1.9.6` is quite outdated by now :) 
Managed reproduce the problem with the instructions given :+1:

Will mark as a bug as this shouldn't happen in the first place.

**Comment by pekkakortelainen** [comment]
Thanks for the heads up, edited the version number.

**Comment by Moppa5** [comment]
At least I wasn't very successful at reproducing this issue, is this still relevant issue? On local vagrant and on my own site no issue. Using Ubuntu 20.04 and Firefox. Could this be somehow browser / os related bug?
