### ISSUE TITLE
Page opened in the same windows

### ISSUE THREAD

**Issue by SailaOrvokki** [Seravo/seravo-plugin#338]
If I go WP dashboard and e.g. go to tools menu, take there database and click like` Lue lisää Adminerista`, it was better if that page opens to a new windows instead of same windows.

![kuva](https://user-images.githubusercontent.com/46742192/76085185-379fd980-5fba-11ea-84a9-236b83a50158.png)

I think that links should open to new window if they are from other source.

**Comment by JoosuaKoskinen** [comment]
I agree! :+1: Quite annoying when they take over the tab.

I used `egrep -nrE . --include \*.php -e 'href' | grep -v _blank` to find some of the links to other sites. These are some of the lines which might have this issue:
```
./modules/database.php:113
./modules/database.php:126
./modules/instance-switcher.php:200
./modules/passwords.php:118
./modules/passwords.php:120
./modules/security.php:315
./modules/security.php:336
./modules/upkeep.php:158
./modules/upkeep.php:175
./modules/upkeep.php:612
./modules/sitestatus.php:303
./modules/sitestatus.php:367
./modules/sitestatus.php:387
./modules/sitestatus.php:450
./modules/check-https.php:39
./lib/sitestatus-ajax.php:83
```

Note that most of the links are translated so the translations must be fixed too.

**Comment by sjaks** [comment]
Closed in https://github.com/Seravo/seravo-plugin/pull/358.
