### ISSUE TITLE
Domains page does not update primary information after primary change

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#354]
**Describe the bug**
After changing the primary domain on domains page, the site does not update the domain information. Then, the primary domain information is displayed on a wrong domain.

**To Reproduce**
1. Go to '/wp-admin/tools.php?page=domains_page'
2. Click on 'Make Primary'
3. Proceed
4. See, that the primary label does not change domain

**Expected behavior**
Primary domain label would be shown on the new primary domain immediately after update.

**Comment by JoosuaKoskinen** [comment]
I can't reproduce this, the primary domain label is always shown on the correct domain on my test site. Can you DM me the details?

**Comment by elguitar** [comment]
I tested in production, it seems to work out just fine! :D Closing
