### ISSUE TITLE
Add SVG support

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#356]
The WordPress core does not support uploading SVG images to the media library: it is disabled by default due to security concerns.

SVG is however a great file format for the type of graphics that can use it (computer graphics, logos, drawings, other vector – many PNG images could be SVG). Nowadays even I[nternet Explorer support SVG](https://caniuse.com/#feat=mdn-svg_elements_svg), so there is no need to postpone adopting SVG images.

Some people install https://wordpress.org/plugins/svg-support/ to get SVG support. Basically it is just 10-20 lines of code that is needed, we could consider adding that to the Seravo Plugin and encourage everybody to use SVG.

In addition to having SVG support via Seravo Plugin, we could automatically sanitize them via [Scour](https://github.com/scour-project/scour/) in future if/when [Scour adds those SVG sanitization features](https://github.com/scour-project/scour/issues/254).

**Comment by nellileinonen** [comment]
Because of the security concerns, should we only allow the users with administrator role to be able to upload SVG images?

The SVG sanitizer (https://github.com/darylldoyle/svg-sanitizer) that @ottok mentions in the Scour's issue has GPL-2.0 license. Because Seravo plugin has GPL-3.0 it can't be directly used.

**Comment by elguitar** [comment]
For now, the safe way to go is to allow SVGs for admins only.

Once a good sanitizing process is implemented, it is easy to broaden the ability to upload SVGs for everyone.

We can go around the licensing problem by running `scour` on the command line since for example `exec('scour something');` is not linking, or by implementing the sanitizer outside of seravo-plugin.

Please proceed with the finalizing :) We will see if the sanitization function is implemented in scour and act accordingly.

**Comment by ottok** [comment]
The wp-image-optimizer could be extended to run scour. The image optimizer
is anyways already run on all image uploads (but currently not for SVG, as
it is not part of the native WP image processing pipeline).

Note however that scour is not a sanitizer, just an optimizer.

Since this plugin is ours (and license is dictated by us) and the
theoretical question is the GPLv2+GPLv3 compatibility, I don't think there
are any legal risks here, using the library is also fine.

**Comment by nellileinonen** [comment]
Administrators can now upload SVG images to media library. SVG is not sanitized. Using library with incompatible licence doesn't feel like the right thing to do.

**Comment by ottok** [comment]
We have now partial SVG support implemented, but not on the level that customers could stop using https://wordpress.org/plugins/svg-support/ yet, so re-opening issue. One should not close an issue if it is not solved, or alternatively if the original issue is closed, then open a new issue for remaining stuff/next tasks.

And, as said, there are no legal risks here. Don't let yourself be restricted of implementing a good solution by a theoretical license issue. Anyway, changed the license now in a3f6864fefd2607603153957e5c65b980776a351.

**Comment by ottok** [comment]
> The SVG sanitizer (https://github.com/darylldoyle/svg-sanitizer) that @ottok mentions in the Scour's issue has GPL-2.0 license. Because Seravo plugin has GPL-3.0 it can't be directly used.

I checked this now and this is not true, the library is and has been GPL 2+ all the time:
https://github.com/darylldoyle/svg-sanitizer/commit/c23fcebe0b9de9444f4722ab36243f00e912ff27

**Comment by nellileinonen** [comment]
Oh, you are totally right. I'm sorry to have caused the trouble and will add the sanitizer to SVG images.

I should have double checked this license version thing and will do so in the future. Now I just mistakenly trusted the first source where I saw information about the license which was the GitHub page of the repository:
![Screenshot from 2020-08-06 10-20-49](https://user-images.githubusercontent.com/43380229/89502988-90c0a300-d7ce-11ea-8488-973f726298df.png)
I can't say why, but I just blindly trusted it would say "GPL-2.0 or later" or "GPL-2.0+" in the GUI as well if that was the state of the license.

**Comment by nellileinonen** [comment]
Feature merged to master
