### ISSUE TITLE
Log files end up in random paths

### ISSUE THREAD

**Issue by ypcs** [Seravo/seravo-plugin#378]
Please, don't do this. As this plugin is only used in Seravo environment, maybe just define log directory somewhere, eg. `define('SERAVO_LOG_DIRECTORY', '/data/log');` and then use that as basis for setting up correct path. Now logfiles can be found from lots of parent directories if someone executes WP CLI in child directory.

https://github.com/Seravo/seravo-plugin/blob/7944fcb01598b5502e332e760c73920545b0e379/modules/wp-plugin-log.php#L80-L86

Example: If someone executes WP CLI in home directory, `/home/wp-settings.log` appears.

**Comment by ypcs** [comment]
While at it, please also fix the original code in 
https://github.com/Seravo/seravo-plugin/blob/7944fcb01598b5502e332e760c73920545b0e379/modules/wp-login-log.php#L66-L71

**Comment by ottok** [comment]
Agree with Ville, just always read '/data/log', it is a and will be the
standard location for the logs this tools is intended to read. (And no need
to add an extra abstraction layer with a constant name as it will not
change, just use the path directly for brevity.)

**Comment by Wiljami** [comment]
Made changes to both wp-plugin-log.php and wp-login-log.php to set the log path to fixed '/data/log/'. Not the most elegant solution, but in line with Otto's thought.
