### ISSUE TITLE
Replace or hide WordPress PHP nag

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#388]
**Description**
WordPress nags about old PHP versions on the WP-admin Dashboard. The link to the WordPress' doc about PHP versions is not helpful at all for Seravo customers.

**To Reproduce**
1. Change PHP version to 7.0
1. Go to wp-admin front page

**Expected behavior**
Seravo should show a similar nag instead of the WordPress default one. It should have Seravo specific information on how to change the PHP version.

**Screenshots**
![phpnag](https://user-images.githubusercontent.com/16290563/87008302-3979e380-c1cc-11ea-8340-63ba400875b4.png)

**Comment by j-falk** [comment]
There are possibilities eg to change the url of that link and other tweaks that can be done, read more on https://make.wordpress.org/core/2019/01/14/php-site-health-mechanisms-in-5-1/

> the link can be adjusted via either an environment variable WP_UPDATE_PHP_URL intended for hosting providers or a filter wp_update_php_url for a more dynamic approach on the code level. Replacing the URL should happen in cases where a more specific guide to update PHP on the given environment exists.

Might also be other possibilities that I have not catched up with.

**Comment by Wiljami** [comment]
Setting the environment variable looks like the easier and faster solution. However it only takes one link and since there could be instructions in different languages this might not be suitable. That's where the wp_update_php_url filter would be needed.
