### ISSUE TITLE
Show an UI for easy review/delete of cuft files

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#39]
Scan for cruft files inside the `/data` directory. For example:

- directories or zip or tar.gz packages called *siirto* or *migration*
- any .sql files apart from the actual relevant dump in /data/db/
- leftovers from w3 total cache, backup plugins etc that are no longer needed

Files like *.hhvm.hhbc* we can go ahead and safely delete immediately. Don't scan for them in this UI, we will scan them otherwise and delete. The purpose of this UI is to scan and view files that the user might find valuable and does not want to delete, though the majority of the suggestions are real cruft that the users will agree to delete when we make it easy enough for them to review the list of files and press _Confirm removal_ or something.

**Comment by simoke** [comment]
Useful commands to find cruft files and directories:

- `for cruft in $(find /ldata/sites/ -name .hhvm.hhbc); do ls -lah $cruft; done`
- `cd /ldata/sites; find -type d -name siirto*`
- `cd /ldata/sites; find -name *.sql*`

**Comment by ottok** [comment]
Backup on migration plugin data storage locations:
```
wordpress/htdocs/wp-content/plugins/all-in-one-wp-migration/storage
wordpress/htdocs/wp-content/ai1wm-backups
wordpress/htdocs/wp-content/uploads/backupbuddy_backups
```

**Comment by ottok** [comment]
More:
```
wordpress/htdocs/wp-content/wp-clone
wordpress/htdocs/wp-content/backupwordpress-*
cd /data/; find -type d -name 'palautus*'
cd /data/; find -type d -name '*vanha*'
cd /data/; find -type d -name '*-old'
cd /data/; find -type d -name '*-copy'
cd /data/; find -type d -name '*-2'
cd /data/; find -type d -name '*.bak'
cd /data/; find -name '*.gz'
cd /data/; find -name '*.zip'
```

Also warn is duplicate `uploads` or `wp-contents` folders are found, which are not symlinks to each other.

**Comment by ottok** [comment]
Also notify customers about `wp core verify-checksums` warnings about files that should not exist, e.g.
```
Warning: File should not exist: wp-includes/js/tinymce/plugins/wpembed/plugin.min.js
Warning: File should not exist: wp-includes/js/tinymce/plugins/wpembed/plugin.js
Warning: File should not exist: wp-includes/js/tinymce/plugins/media/moxieplayer.swf
```

**Comment by ottok** [comment]
@simoke Please update the status of this issue

**Comment by ottok** [comment]
Another one is the plugin _updraftplus_ that creates a folder called _updraft_ that has the backup files.

**Comment by simoke** [comment]
The first version of the cruft remover is now published and discussion of improvements and fixes are in #85

**Comment by ottok** [comment]
Are all the checks listed above implemented?

**Comment by simoke** [comment]
The feature is fully implemented in Seravo Plugin.
