### ISSUE TITLE
Database chart should use Apex Charts and be clearer

### ISSUE THREAD

**Issue by sjaks** [Seravo/seravo-plugin#397]
The charts introduced in https://github.com/Seravo/seravo-plugin/pull/393, https://github.com/Seravo/seravo-plugin/pull/392, https://github.com/Seravo/seravo-plugin/pull/391 and https://github.com/Seravo/seravo-plugin/pull/396 use Apex Charts as their chart library. There is now one chart on the Database page that still uses Chart.js.

The Database chart acts in an odd way because of an upstream bug, see issue https://github.com/Seravo/seravo-plugin/issues/380.

A pie chart is also a bad choice for such a chart, so maybe the type should also be changed. The Disk space chart was transformed into a bar chart and it seems quite clear. Maybe a bar chart could be used here.

Bar chart example:
![Screenshot from 2020-07-14 12-06-27](https://user-images.githubusercontent.com/44066308/87407179-7d088f00-c5ca-11ea-9f33-cc532a01374c.png)

Currently, the chart looks like this and is hard to read:
![](https://user-images.githubusercontent.com/44066308/86130997-b7176280-baed-11ea-9693-90fdbdb5662b.png)

**Comment by Moppa5** [comment]
The proposed chart is likely to be at least more clearer when looking the database size as individual tables. Yet still I think that some kind of pie chart could be there as it's nice for visualizing too. Nevertheless, for consistency this proposed chart is much better :)

**Comment by sjaks** [comment]
The bar chart can potentionally grow so large, it could mess up the Databse page. If it is used, the chart should be put into a wrapper of fixed height and set the overflow of the chart to be scrollable.

@Moppa5 I agree that it is difficult to see the relativity of the sizes here. What takes the highest percentage and so on. I am tyring to think if it's important to the user.

I think the important features of the chart are
- ability to see the largest tables
- ability to see the size of a specific table when debugging something

The bar chart example above already provides these features. Do you have ideas what a bar chart could provide?

(Or a donut chart: https://charting-ahead.corsairs.network/doughnuts-vs-pie-a-visual-primer-629b846aac67)

**Comment by sjaks** [comment]
I was experimenting with a scroll bar. The scroll bar is essential if there are hundreds of tables. However, the default site has just a few and an installation with Woocommerce, also only a handful, so the height shouldn't ne fixed but a `max-height` should be set. The value could be automatically derived from the window height but this could require JS. A fixed max-height is enough, in my opinion.

![Screenshot from 2020-07-15 09-20-44](https://user-images.githubusercontent.com/44066308/87510575-7fc3bc80-c67c-11ea-85ee-699b264d02a2.png)

Before I continue taking this further, the preferred type of chart should be discussed. Also, should there be a chart that shows the relation (pie/donut)?
