### ISSUE TITLE
Allow users to browser (and follow!) logs from WP-admin

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#42]
Work in progress at https://github.com/Seravo/seravo-plugin/tree/feature-logs-page

@l3ku and @elguitar could finalize it.

**Comment by ottok** [comment]
@l3ku Please update the status of this issue

**Comment by l3ku** [comment]
Logs are now accessible via wp-admin in Tools > Logs. There are still some minor tweaks that could be made for the GUI, like actually increasing the number ("Showing %s rows") when reloading more log rows via AJAX when scrolling up, for instance. Also the appearance could be tweaked to almost perfection.
However, I think it is smarter to keep the current state of the beta log tool and wait for more thorough feedback from our customers, and include these among the other improvements that will be made.

**Comment by l3ku** [comment]
What is your view on this @ottok, can the issue be closed?

**Comment by ottok** [comment]
In production. Later improvements via separate issues, designs and rationales.
