### ISSUE TITLE
There is no feedback on abnormal log files

### ISSUE THREAD

**Issue by Wiljami** [Seravo/seravo-plugin#422]
Right now if the log files are too large there is no feedback to the user.

If for example the log file is not parsed because of the size, the user should be informed of this instead of getting no feedback.

Related #416

**Comment by Moppa5** [comment]
There's the site error status box on wp admin dashboard and I think we could have similar notification about abnormal log files, see issue #7. It would be of course good to have some output on logs page if the log can't be viewed.

**Comment by Wiljami** [comment]
Yes. The site error status is what is reading the error log to begin with and potentially causing the freezes. If the log can't be read, it would be logical to display this error in the same place as well.
