### ISSUE TITLE
Database detail box shows really large autoload table size

### ISSUE THREAD

**Issue by sjaks** [Seravo/seravo-plugin#431]
The Details box under Database page in Seravo Plugin shows the total size of the autload options table. The size unit magnitude must be wrong since a really light-weight site has a size of over 70 MB, which is exceptionally high for any site.

![Screenshot from 2020-08-07 09-59-44](https://user-images.githubusercontent.com/44066308/89618526-f9725300-d894-11ea-9ff7-c5ed53af9c44.png)

**Comment by ottok** [comment]
Sami: run `ncdu -x /data` so review yourself where the 70 MB comes from.

If you do some fixes related to this, then please also drop the extra
decimals. For a number like this "70 MB" is enough, the ".032" is just
extra clutter without value.

**Comment by sjaks** [comment]
Changed the divisor from 10^3 to 10^6 already. The number 70 MB was wrong and should be by factor 10^3 lower.

It is a good idea to round the number!

**Comment by elguitar** [comment]
Here are some examples of autoload usages:
new site: 0,015 MB
my site: 0,054 MB
large site: 0,714 MB

**Comment by sjaks** [comment]
Currently my site looks like this via Seravo Plugin:
![Screenshot from 2020-08-07 11-17-53](https://user-images.githubusercontent.com/44066308/89624939-ac47ae80-d89f-11ea-94f3-f131ea75e990.png)

Maybe two (max three) decimals is enough.

**Comment by sjaks** [comment]
![Screenshot from 2020-08-10 10-23-15](https://user-images.githubusercontent.com/44066308/89759889-d09bc900-daf3-11ea-80f0-cced8e920a68.png)

I thin two decimals is the way to go: https://github.com/Seravo/seravo-plugin/pull/436
