### ISSUE TITLE
Missing php-error.log interpret as abnormally large

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#441]
**Describe the bug**
After cleaning up my own site I stumbled upon this little bug of abnormally large php-error.log when the actual case is that the file is missing. 

**To Reproduce**
1. Go to /data/log
2. Remove php-error.log file
3. Go to wp admin dashboard

**Expected behavior**
There should be some kind of check for not showing "abnormally large" message if the file doesn't exist. Maybe even prompt user on dashboard with something like "php-error.log is missing or deleted". It could also create empty php-error.log if it's missing. 

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/16706187/90245408-4927c000-de3b-11ea-85ac-23d9fcb5e24f.png)

**Comment by Wiljami** [comment]
Right now the feedback for an error-log that can't be read is that. So really what needs to be done is to give relevant feedback to the user depending on the type of error.

**Comment by Wiljami** [comment]
Closed by #455
