### ISSUE TITLE
PHP Notice: Undefined index: HTTP_X_SERAVO_REQUEST_ID

### ISSUE THREAD

**Issue by thejulle** [Seravo/seravo-plugin#462]
We get the following PHP notice from seravo-plugin in local dev environment:

> PHP Notice:  Undefined index: HTTP_X_SERAVO_REQUEST_ID in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/modules/thirdparty-fixes.php on line 64

WP 5.6
seravo-plugin 1.9.25
PHP 7.4.12

`$_SERVER['HTTP_X_SERAVO_REQUEST_ID']` is used without checking if it's set.

Should be changed to something like this:
`(isset($_SERVER['HTTP_X_SERAVO_REQUEST_ID']) ? $_SERVER['HTTP_X_SERAVO_REQUEST_ID'] : null)`

**Comment by ypcs** [comment]
Thanks for the report @thejulle! This was, as you can see, fixed in master, and fix will be included in next stable release. :)
