### ISSUE TITLE
Nag if object-cache.php is missing

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#463]
Using Redis for transients etc is a major performance improvement. Some sites however don't have object-cache.php in place for various reasons.

Seravo Plugin could nag about it, and provide an easy one-click way to re-install the latest object-cache.php version in place.

**Comment by elguitar** [comment]
First step should be to implement the nag thing. Only after that is implemented, should the extended features be implemented (one-click install etc.)

**Comment by elguitar** [comment]
To get started, `modules/check-https.php` can be used for reference :)

**Comment by elguitar** [comment]
If you find the nag bar too offensive, the nag could be implemented to wp-admin/tools.php?page=site_status_page.

@Moppa5 what do you think?

**Comment by Moppa5** [comment]
@elguitar, I think it's a good idea. In my opinion the nag bar as "admin notice" might be irritating. I will continue implementing it on the site status page instead.
