### ISSUE TITLE
Instance switcher javascript code assumes all links in dropdown point to a shadow

### ISSUE THREAD

**Issue by danielck** [Seravo/seravo-plugin#47]
At least in situations where there are no shadows, the toolbar dropdown menu for the instance switcher shows a link "Shadows explained at seravo.com/docs". Clicking this item does not take you to seravo.com/docs as one would assume, but instead sets the `wpp_shadow` and `seravo_shadow` cookies with the value `https://seravo.com/docs/deployment/shadows/` and then reloads the page, which in my case resulted in a scary 500 error, presumably because the server was trying to show me a shadow instance that didn't exist or was broken. 

The culprit is instance-switcher.js, which assumes that all items in the dropdown point to shadow-related tasks (i.e. either point to a shadow or exiting one).

You should definitely fix this as it can be quite a scary experience for someone who clicks on that link by mistake and doesn't have pre-existing knowledge of how your shadows work.

**Comment by ottok** [comment]
The issue is now fixed. You can update to the latest development version with `wp-seravo-plugin-update --dev` or wait until version 1.6.0 is published.

Thanks @danielck for reporting!
