### ISSUE TITLE
"Running cache tests..." permament despite of success or failure

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#470]
**To Reproduce**
1. Go to 'Site status'
2. Click on 'Run cache tests'
3. "Running cache tests..." should stay permanently even though the wrapper color indicates success or failure 

**Expected behavior**
The "Running cache tests..." and the spinner gif should be gone and changed to either success or failure message.

**Screenshots**
![running_tests](https://user-images.githubusercontent.com/16706187/106457691-0369bd00-6498-11eb-8281-793530376739.png)

**Comment by elguitar** [comment]
I am unable to reproduce the issue. Does running `wp-check-http-cache` from the terminal hang too?

**Comment by Moppa5** [comment]
@elguitar, the command works correctly, and as we can see the "green bar" is there to indicate "success". On the other hand, I think this might be a browser related bug. I will try another browser to see if the same occurs.

**Comment by elguitar** [comment]
Funny.. I tested this on your site and I managed to reproduce the issue. Running on Firefox 78 with Opensuse Leap 15.2.

**Comment by elguitar** [comment]
Tested this on a fresh customer site too and the spinner keeps on going.

**Comment by Moppa5** [comment]
@elguitar, I noted that you can actually see the "HTTP cache working" text there just slightly before the "Running cache tests..." appears. Thus my conclusion is that this might be some kind of JavaScript async related bug where it executes the result (success or failure) before putting the running on. This seems to be related to lightweight pages where there's not much content so running cache tests takes only milliseconds.
