### ISSUE TITLE
Put defaults on sites that don't have any values set manually

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#472]
Currently on all new sites the [installer.php in Seravo/WordPress](https://github.com/Seravo/wordpress/blob/master/htdocs/wp-content/install.php#L610-L619) sets the image optimizer and other features on by default for new sites.

The settings are WordPress options, stored in the database. However, if a new site is migrated, along comes its database and these settings disappear.

I propose that Seravo Plugin would sniff if these settings have any value set, and it they don't exists at all, it would set a default value. Such a behavior would make the default apply to both new sites, migrated sites as well as old sites.

Since the defaults are pretty sane and have served us well, having them apply to old sites as well seems pretty safe and sensible at this point.

**Comment by elguitar** [comment]
The options that need to be set are found in https://github.com/Seravo/wordpress/blob/master/htdocs/wp-content/install.php#L610-L619

Docs for handling options in WP: https://developer.wordpress.org/reference/functions/get_option/

You can add a new module and include it in `seravo-plugin.php`.

**Comment by ottok** [comment]
Follow-up PR filed at https://github.com/Seravo/wordpress/pull/177
