### ISSUE TITLE
PHP Fatal error and warnings on Seravo Plugin pages with PHP8

### ISSUE THREAD

**Issue by pekkakortelainen** [Seravo/seravo-plugin#478]
Browsing through Tools pages provided by Seravo Plugin results in a fatal error on Domains page and warnings on other pages when running PHP8. 

**Steps to reproduce:**

1. Set PHP mode to 8.0 in `/data/wordpress/nginx/php.conf`
2. Restart NGINX: `wp-restart-nginx`
3. Use `wp-watch-php` or `tail -f /data/log/php-error.log` to monitor PHP error log
4. Browse through pages provided by Seravo Plugin in wp-admin and monitor the PHP error log simultaneously

**Found errors and warnings:**

Domains page
```
PHP Fatal error:  Uncaught TypeError: date_format(): Argument #1 ($object) must be of type DateTimeInterface, bool given in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domain-tables.php:98
Stack trace:
#0 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domain-tables.php(98): date_format(false, 'j.n.Y H:i')
#1 [internal function]: Seravo_Domains_List_Table->column_expires(Array)
#2 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/list-table.php(1357): call_user_func(Array, Array)
#3 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domain-tables.php(274): Seravo\WP_List_Table->single_row_columns(Array)
#4 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/list-table.php(1289): Seravo_Domains_List_Table->single_row(Array)
#5 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/list-table.php(1274): Seravo\WP_List_Table->display_rows()
#6 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domain-tables.php(294): Seravo\WP_List_Table->display_rows_or_placeholder()
#7 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domains-ajax.php(23): Seravo_Domains_List_Table->display()
#8 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domains-ajax.php(313): seravo_get_domains_table()
#9 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(287): seravo_ajax_domains('')
#10 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#11 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#12 /data/wordpress/htdocs/wordpress/wp-admin/admin-ajax.php(184): do_action('wp_ajax_seravo_...')
#13 {main}
  thrown in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domain-tables.php on line 98
```

Upkeep page
`PHP Warning:  Undefined array key "report" in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/seravo-plugin.php on line 142`

Multiple pages
`PHP Warning:  Undefined variable $container_class in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/seravo-postbox.php on line 255`

**Comment by Moppa5** [comment]
I think that #486 is actually related to this issue as well. At least the `undefined array key "report"`

**Comment by Moppa5** [comment]
The mentioned `PHP Warning: Undefined array key "report"` is now fixed by #491. 

PHP error seems to be on these lines
```
public function column_expires( $item ) {
    $expires = $item['expires'];
    if ( ! empty($expires) ) {
      $timestamp = date_create_from_format('Y-m-d\TH:i:sO', $expires);
      return date_format($timestamp, get_option('date_format') . ' ' . get_option('time_format'));
    }
  }
```
For some reason `$timestamp` returns false since the `$expires` seems not to be a valid. This could be easily fixed by either checking whether the `$timestamp` is false or by extending the `!emtpy($expires)` check with valid date check. 

Also, I found on a test site that there's similar undefined array key warning
`[12-Mar-2021 10:23:39 UTC] PHP Warning:  Undefined array key "subdomain" in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/lib/domain-tables.php on line 205`

**Comment by Moppa5** [comment]
Closing this as 8a39392 fixes the reported `undefined array key "report"` and 452abc2 fixes the PHP fatal error on domains page. As mentioned earlier the `undefined array key "hook_suffix"` might be something that can't be fixed on seravo plugin and thus should be worked on a separate issue / case.

**Comment by Moppa5** [comment]
Updating here, #518 includes a fix to the `undefined array key "hook_suffix"` PHP warnings.
