### ISSUE TITLE
1.9.28 breaks REST-API users route

### ISSUE THREAD

**Issue by spktklr** [Seravo/seravo-plugin#513]
Updating to 1.9.28 breaks /wp-json/wp/v2/users, resulting in `"rest_no_route"`.

Using 1.9.27 for now.

**Comment by JoosuaKoskinen** [comment]
Disabling `/wp-json/wp/v2/users` endpoint is a security feature which is now enabled by default. You can turn the feature off through wp dashboard by going to `Tools` > `Security` > `Disable WP-JSON user enumeration`.

**Comment by spktklr** [comment]
> Disabling `/wp-json/wp/v2/users` endpoint is a security feature which is now enabled by default. You can turn the feature off through wp dashboard by going to `Tools` > `Security` > `Disable WP-JSON user enumeration`.

Are there release notes for this breaking change? Is there a mailing list where you inform your customers of future breaking changes?
