### ISSUE TITLE
Unable to turn off "Disable WP-JSON user enumeration"

### ISSUE THREAD

**Issue by spktklr** [Seravo/seravo-plugin#514]
**Describe the bug**
Unable to turn off _Disable WP-JSON user enumeration_.

**To Reproduce**
1. Go to Tools > Security 
2. Click on Disable WP-JSON user enumeration.
3. Save changes
4. See changes not being applied

**Expected behavior**
Changes applied

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome, FireFox
 - Latest versions

**Comment by elguitar** [comment]
I managed to reproduce this. Affects seravo-plugin 1.9.28.

This is because the form sets the values to "on" or "" (empty string). Empty string is considered the default and it is replaced.

I am fixing this right away to avoid hassle in the future.
