### ISSUE TITLE
More informative dashboard widgets

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#517]
**Description**
There has been discussion about wp-admin dashboard widgets. Especially it was requested that there could be more informative and notification stylish widgets for instance warning regarding usage of PHP version that is soon EOL, low disk space etc. More over the current PHP error count notification could be integrated with EOL PHP version warning. 

**Implementation**
Currently the #5 dashboard widget is implemented on login-notifications.php. However, in order for the login-notifications.php not becoming too large I'd propose that there would be some kind of dashboard_widgets class acting as a helper or completely for the widgets. This way we can implement the widgets and notifications separately as well. What do you think? 

**Additional context**
See #5 and #508 as examples

**Comment by Moppa5** [comment]
There is now a class for dashboard widgets implemented on branch [`feature/dashboard-widgets`](https://github.com/Seravo/seravo-plugin/tree/feature/dashboard-widgets). As mentioned on this issue it might be better implementing these dashboard widgets separately from login notifications thus the new class. 

What do you think @JoosuaKoskinen and @elguitar?

**Comment by JoosuaKoskinen** [comment]
Large files are no problem but for keeping the project structure nice and modular, it's a good change.

:+1: from me

**Comment by Moppa5** [comment]
To sum up, this far dashboard widgets include
- PHP error count notification
- PHP EOL notification integrated with PHP error widget
- Low disk space notification if the plan is using more than 90% of the space

**Comment by Moppa5** [comment]
Closing this issue as the foundations for extending and implementing new dashboard widgets have been made. We can make separate concrete issues about new features / widgets.
