### ISSUE TITLE
Images in RSS feed are not displayed with absolute URLs

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#52]
A customer reported that the RSS feed image URLs are not appearing as absolute URLs, which results in the images not displaying at all. He was able to solve this problem by generating the img tags himself:
```
$content = '<div> <img src="' . get_site_url( null, get_the_post_thumbnail_url( $post->ID, 'medium')) 
. '" class="attachment-medium size-medium wp-post-image" alt="' . get_the_title( $post->ID ) . '" 
style="margin-bottom: 15px;"></div>' . $content;
```
It was also reported, that the use of the filter ```add_filter('seravo_use_relative_urls', '__return_false');```did not solve the problem. Is this problem then caused by Seravo Plugin?

**Comment by ottok** [comment]
Have you tried disabling `define('WP_CONTENT_URL', CONTENT_DIR);`

https://github.com/Seravo/wordpress/blob/master/htdocs/wp-config.php#L46-L48

**Comment by l3ku** [comment]
Disabling ```define('WP_CONTENT_URL', CONTENT_DIR);``` solved the problem, closing the issue.
