### ISSUE TITLE
Try automatic refactoring

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#527]
In https://github.com/wp-cli/wp-cli/pull/5528, wp cli project did multiple small refactoring changes in order to remove technical debt.

We should see if the tool used (https://github.com/rectorphp/rector) would be helpful for seravo-plugin.

**Comment by JoosuaKoskinen** [comment]
Good idea! I already did some testing with it. There's few sections of code where it gets confused and makes weird proposals, for example:
```
@@ @@
       <?php elseif ( ! $result ) : ?>
         <p><?php _e('Log empty', 'seravo'); ?></p>
         <?php
+        // result -1 is the signal that something went wrong with reading the log<?php
         // result -1 is the signal that something went wrong with reading the log
         elseif ( $result === -1 ) :
         ?>
@@ @@
```

But no wonder, even I get confused with that section:
```
      <?php elseif ( ! $result ) : ?>
        <p><?php _e('Log empty', 'seravo'); ?></p>
        <?php
        // result -1 is the signal that something went wrong with reading the log
        elseif ( $result === -1 ) :
        ?>
        <p><?php _e('Log is broken and can not be displayed.', 'seravo'); ?></p>
      <?php else : ?>
        <p><?php _e('Scroll to load more lines from the log.', 'seravo'); ?></p>
        <?php
      endif;
```

Definitely not bulletproof tool but with correct configuration it could be very helpful. So far it has made a lot of smart decisions.

**Comment by JoosuaKoskinen** [comment]
Made an upstream issue to see what they think: https://github.com/rectorphp/rector/issues/6443

**Comment by Moppa5** [comment]
Closing this issue as it seems that Rector is here to stay and the new development tools have been merged to master. We can discuss Rector specific issues or improvements separately.
