### ISSUE TITLE
Create helpers and unify the style

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#538]
**Description**
As discussed in an internal issue the Seravo Plugin has many ways of creating different components like texts for instance. We should discuss, design and implement a way to create these more dynamically. There were ideas considering some sort of JS library for creating JavaScript and AJAX posts more dynamically. We should investigate the CSS styling in Seravo Plugin as well since there could most likely be only one commons CSS for all the pages. 

These changes are sort of pending on the new design after cleanup, but we need to plan these a little beforehand.

**Comment by Moppa5** [comment]
@JoosuaKoskinen, Could you clarify & wrap up here what kind of helpers should be implemented after the #545 is merged?

**Comment by JoosuaKoskinen** [comment]
Some of the helpers needed under template.php:

[ ] paragraph
[ ] title
[ ] button
[ ] options field 
![settings](https://user-images.githubusercontent.com/42264063/122210851-c2a29b80-ceae-11eb-87a3-00d316060985.png)
[ ] result wrapper
![result](https://user-images.githubusercontent.com/42264063/122210992-ea91ff00-ceae-11eb-86e2-46d16b3befcb.png)
[ ] some basic table
![table](https://user-images.githubusercontent.com/42264063/122211118-0ac1be00-ceaf-11eb-9fed-3fac0215c496.png)
[ ] slider thingy (Tools >  Upkeep > Screenshots)
[ ] success/failure (with bool as input)
![success](https://user-images.githubusercontent.com/42264063/122211376-55dbd100-ceaf-11eb-8d75-5527440ebecf.png)
[ ] the spinner gif

They should have options to give id and class too if it might be needed.

**Comment by Moppa5** [comment]
Options field needs some thinking and might be the best to be implemented when converting a widget that uses it. There's quite good guide here https://developer.wordpress.org/plugins/settings/settings-api/ available.

**Comment by Moppa5** [comment]
@JoosuaKoskinen, Are you working with the wrapper thing? I would say that it's something we need next as there are quite many widgets using it.

**Comment by Moppa5** [comment]
Closing this issue as most of the helpers are already created and those that are needed in future will therefore be created as well.
