### ISSUE TITLE
Change the base class of Seravo_Domains_List_Table

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#54]
In WP Codex it is said that the class WP List Table is not intended for development use:
_"This class's access is marked as private. That means it is not intended for use by plugin and theme developers as it is subject to change without warning in any future WordPress release. If you would still like to make use of the class, you should make a copy to use and distribute with your own project, or else use it at your own risk."_ source: https://codex.wordpress.org/Class_Reference/WP_List_Table 

We should find a better option or fork it in case of big changes in upstream.

**Comment by ottok** [comment]
I have no opinion on this. If we fork it, we might still want to import the latest "upstream" release from version to version anyway. I guess it depends on what features we use from the class.

**Comment by elguitar** [comment]
This can be seen as a subtask of #12 since the domains page will require significant alterations anyway. This issue should be resolved too when updating the page.

**Comment by ottok** [comment]
@JoosuaKoskinen Could you check if this still needs to be addressed, and if so, fix it? Thanks!

**Comment by JoosuaKoskinen** [comment]
This is still the case and I think we should fork `WP_List_Table`. It has had 9 commits made in the past 12 months and it's just a matter of time when it has a breaking change (and following WordPress standards is not a bad thing).

Also, currently only domains table uses `WP_List_Table` but email forwards might do that soon too so it makes sense to have our own version of it.

One con is that we probably have to update the forked file from time to time if it has had major improvements made to it upstream.

Will do the forking soon if nobody resists.

**Comment by elguitar** [comment]
Pending for the mail forwards PR to be merged at https://github.com/Seravo/seravo-plugin/pull/372
