### ISSUE TITLE
Enable instance switcher for non-admins (or provide an easy way to do it)

### ISSUE THREAD

**Issue by elguitar** [Seravo/seravo-plugin#55]
There was a request for enabling instance switcher for non-admins.

**Comment by szepeviktor** [comment]
You may hook caps in `admin_bar_menu`.
An example
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-menu-edit-for-editors/menu-for-editors.php

**Comment by elguitar** [comment]
Fixed in 91911ee
