### ISSUE TITLE
Test with Network

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#57]
The plugin needs to be tested with Network installs a bit. Currenlty there is for example the problem, that in Network installs every subsite gets the Tools menu and actions (e.g https://seravo.fi/wp-admin/tools.php) when in fact on Network installs it would probbly make sense to disable access from subsites and only expose the Seravo Plugin stuff in the Network admin (e.g https://seravo.fi/wp-admin/network/) for super-admins?

**Comment by elguitar** [comment]
Fixed in 8d33450d2f3cff52fe78730125723ea6327799ec
