### ISSUE TITLE
Wrong variable name in relative-urls.php

### ISSUE THREAD

**Issue by msaari** [Seravo/seravo-plugin#58]
Line 100 in /modules/relative.urls.php:

`      if ( (isset($_SERVER['HTTP_PRAGMA']) && $_SERVER['HTTP_PRAGMA'] === 'no-cache') || false === ( $content = get_transient( $key ) ) ) {`

There's no variable `$key`; it should be `$transient_key`.

**Comment by msaari** [comment]
This bug had me wondering for couple of hours why my RSS feeds display excerpts instead of full posts. The broken plugin returns empty content, which makes the RSS feed entry content disappear, only to be replaced by a short description.

**Comment by l3ku** [comment]
Thank you for noticing this bug and debugging it!
