### ISSUE TITLE
Collect and show login log

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#6]
All sites should collect a /data/log/login.log file. Consider adopting functionality from https://github.com/nrosvall/wp-login-log

It would also be good to have a menu item where under users can directly from WP-admin view a list of last logins. It could simply just be a login.log parser and prettifier.

**Comment by ottok** [comment]
We now collect wp-login.log for all logins, and we tell users in the dashboard when they last logged in.

One last thing that would be super useful, would be to show on the profile.php page a section that lists the last 10 logins for that user, so that users themselves can view their own history, and that site admins can view the history of whichever user they want.

**Comment by ottok** [comment]
See also discussion in #7

**Comment by l3ku** [comment]
Before we start implementing this, we should reconsider the source for the user login data. As the `wp-login.log` file is regularily rotated, there may be a scenario that the 10 last logins are not found even though the user has most certainly logged in more than 10 times. To me, it makes no sense to start decompressing the previous gzipped logfiles in order to fetch the previous logins.

**Comment by ottok** [comment]
Design outline:
- Extend page `/wp-admin/tools.php?page=security_page` to have a new postbox titled "Recent successful logins"
- Show list or table (depends on Seravo postbox width vs contents width)
- View last 10 logins - or last logins for past 10 days?
- Use latest wp-login.log + logrotated prevous files (/data/log/wp-login.log, -dateext, -dateext.gz)
- Show login time, IP address, username
- Placed in a postbox
- function parameters: username, min and max number of logins wanted, geolocation on/off (so that same function can be used in security screen)
- open logs and parse in php
- Security page is visible only to admin. Thus show all logins. In a later revision consider making some extension to profile.php so that users can see their own logins.
- Use ajax to populate postbox so users don't need to "wait" for the log processing. See reports page for example.
