### ISSUE TITLE
Speedtest available on WP admin bar when user has capability to edit posts

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#616]
**Describe the bug**
Speedtest is available on WP admin bar when user has capability to edit posts (editor, contributor, author). However, the user has no permission on Seravo Plugin and they can't actually run the speedtest. Trying to run the speedtest causes "You don't have permission to view the page" or similar (translated from Finnish).
**To Reproduce**
1. Set user role to editor, contributor or author
2. Notice on WP admin that speedtest is available on the banner
3. Go to some page and try to run speedtest

**Expected behavior**
The speedtest most likely shouldn't be available if it can't actually be run by the user.

**Comment by JoosuaKoskinen** [comment]
Fixed in #636
