### ISSUE TITLE
/data/log not existing causes log page to load forever

### ISSUE THREAD

**Issue by Moppa5** [Seravo/seravo-plugin#621]
**Describe the bug**
If path `/data/log` doesn't exist, it causes the spinner on log page to spin forever. 

**To Reproduce**
1. Go to `/data`
2. Remove `/data/log` folder completely (backup it if you want)
3. On Seravo Plugin go to log page
4. See the spinner spinning forever

**Expected behavior**
User should be prompted that they don't have any logs and `/data/log doesn't` exist.

**Screenshots**
![Screenshot(41)](https://user-images.githubusercontent.com/16706187/130069002-9423dd56-4f32-4f89-a8f9-92a23f2df4cb.png)

**Comment by JoosuaKoskinen** [comment]
Fixed in #630
