### ISSUE TITLE
Administrator role is not enough on multisites

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/seravo-plugin#622]
**Describe the bug**
On multisite, being administrator is not enough to access toolpages, super-admin capabilities are required.
How should it be? Should administrators be able to access all the tools, none of them or only the ones that can't make network wide changes?

Also not being able to access toolpages causes the same as in https://github.com/Seravo/seravo-plugin/issues/616.

**Comment by Moppa5** [comment]
Not quite sure here either. Maybe it was best that the administrators could not make network wide changes? Feels quite weird if administrators can't access any Seravo Plugin tools 🤔

**Comment by JoosuaKoskinen** [comment]
Fixed in #636
