### ISSUE TITLE
Misc issues in development and shadow envs

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/seravo-plugin#626]
**Describe the bug**
- Opening security page in dev env logs following:
```
[19-Aug-2021 14:13:00 UTC] PHP Warning:  Undefined array key 0 in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/cruftremover.php on line 387
[19-Aug-2021 14:13:00 UTC] PHP Warning:  foreach() argument must be of type array|object, null given in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/cruftremover.php on line 389
```

- I think all postboxes on database page should be shown in development and shadow envs, currently only search-replace postbox is shown. The adminer link must be different in dev env though.

- "Backups" postbox should be hidden in development env as it's just information about automatic backups and which apply in development env.

**Comment by Moppa5** [comment]
Cruftremover seems to have many instances of "blindly executing" something in some path. We should go through the whole `cruftremover.php` file for possible issues. 

As the adminer link is now fetched using the Helpers method, it can quite easily be enhanced so that development gets correct link.

**Comment by Moppa5** [comment]
In addition, I stumbled upon an issue on cruft files listing when running locally on development (docker). At least files `/data/wordpress/.vagrant/mariadb.bak` and `/data/wordpress/.vagrant/backup-dump.sql` cause the cruft files listing to emit 
`Error: Something unexpected happened! Server responded with invalid data.`

`Error:  TypeError: category.cruft.forEach is not a function`
Cruftremover.js on line 95: `category.cruft.forEach((cruft) => {`

I couldn't quite find a solution to this but it seems to be somehow related to method as both of the files had empty mod_date.
```
public static function add_file_information( $file ) {
    if ( $file !== Helpers::sanitize_full_path($file) ) {
      return array(
        'size' => '0B',
        'mod_date' => null,
        'filename' => $file,
      );
    }
```

@JoosuaKoskinen, Do you have any thoughts on this?

**Comment by JoosuaKoskinen** [comment]
Issues mentioned here have been fixed in https://github.com/Seravo/seravo-plugin/tree/seravo-plugin-2/fix-cruftremover. But now found that the confirmation modal doesn't show up. No javascript errors or anything.

**Comment by JoosuaKoskinen** [comment]
> But now found that the confirmation modal doesn't show up. No javascript errors or anything.

Can't find any reason for this.`tb_show` doesn't show the modal in development. The HTML etc seems identical.

**Comment by Moppa5** [comment]
@JoosuaKoskinen, it seems that by adding ` \wp_enqueue_style('thickbox', false);` fixes the issue on development. I stumbled upon this when browsing https://wpquestions.com/Wordpress_old_style_thickbox_on_the_page_front_end/8230.

**Comment by Moppa5** [comment]
@JoosuaKoskinen, I also stumbled upon a bug in cruftremover
```
[30-Aug-2021 13:13:34 UTC] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/cruftremover.php:508
Stack trace:
#0 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/cruftremover.php(508): in_array('/data/wordpress...', false, true)
#1 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/modules/pages/security.php(529): Seravo\CruftRemover::remove_cruft_files(Array)
#2 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/modules/pages/security.php(210): Seravo\Page\Security::remove_cruft('files')
#3 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/ajax/handler.php(176): Seravo\Page\Security::Seravo\Page\{closure}('remove-cruft-cr...')
#4 /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/ajax/handler.php(73): Seravo\Ajax\AjaxHandler->_ajax_handler()
#5 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(303): Seravo\Ajax\AjaxHandler->Seravo\Ajax\{closure}('')
#6 /data/wordpress/htdocs/wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 /data/wordpress/htdocs/wordpress/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /data/wordpress/htdocs/wordpress/wp-admin/admin-ajax.php(187): do_action('wp_ajax_seravo_...')
#9 {main}
  thrown in /data/wordpress/htdocs/wp-content/mu-plugins/seravo-plugin/src/lib/cruftremover.php on line 508
```
And the reason lies here with `get_transient` returning false
```
$legit_cruft_files = \get_transient('cruft_files_found'); // Check first that given file or directory is legitimate
if ( \in_array($file, $legit_cruft_files, true) ) {
```
I think it would be wise to fully go through the cruftremover so that the bugs like this are eliminated.

**Comment by JoosuaKoskinen** [comment]
Everything here fixed in https://github.com/Seravo/seravo-plugin/pull/639
