### ISSUE TITLE
Automatically rename uploads with special characters

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#71]
Every now and then we come across sites that suffer from problems because they have ä and ö letters in their URLs.

To fix it at least for media uploads, we could finalize the [automatic renamer](https://github.com/Seravo/wp-rename-uploads) which would automatically transform all _ä_ and _ö_ into _a_ and _o_.

This could be enabled by default or as an opt-in feature of the Seravo Plugin.

**Comment by Wiljami** [comment]
I think there isn't much to be gained from [automatic renamer](https://github.com/Seravo/wp-rename-uploads) anymore. It is old, makes no use of WordPress hooks and it is also a hook from another plugin. By the looks of it there is very little code added to it compared to the hook.
