### ISSUE TITLE
Improve the cache status report

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#72]
Our current Reports page has a very small and naive cache tester section. It could be removed and replaced with a separate page, that makes at least 5 test curls on the website to determine the current HIT/MISS behavior and show a nicely formatted report about the test result. 

There should also be some listing of relevant HTTP headers and pointers to WordPress documentation so developers could more easily grasp what is the status of caching on the site and how they should change their code base.

In addition there could also be a section that shows historical cache HIT/MISS ratios based on data extracted from `/data/slog/`.

**Comment by ottok** [comment]
Current cache status box:
![image](https://user-images.githubusercontent.com/668724/60666699-53be0a80-9e70-11e9-93b5-f8e67abe092f.png)

This should be split into "HTTP cache status" and "Redis cache status".

**Comment by JoosuaKoskinen** [comment]
**Status update:** Will take care of this soon. The toolbox update made changes to almost everything so there's a lot of conflicts to be fixed.

**Comment by JoosuaKoskinen** [comment]
Cache status postbox was improved in https://github.com/Seravo/seravo-plugin/pull/300, closing...
