### ISSUE TITLE
Use custom class for http://localhost:8888 requests

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#77]
We use these requests to get/set information regarding a customer's site, but the functionality is only implemented in the Updates class (as it is currently its only use case). What if in the future we would want to include a new page, where there would be information about shadows, which requires access to this API? We would then have almost the exact same functionality repeated in multiple files.

There should be an individual class file (e.g. SeravoAPI or such) which provides abstraction for making these requests to remove the API request responsibility from the Updates class alone.

**Comment by ottok** [comment]
:+1:
