### ISSUE TITLE
Image optimization default image size should be smaller

### ISSUE THREAD

**Issue by karisavolainen** [Seravo/seravo-plugin#81]
Image optimization resizing default image size is 4000 x 4000px. Most people who would use this feature, do not understand what would be a good size for a web image, so they leave the setting to the default value. 

4000 x 4000 is a bit overkill, to see it in 100% size, you would need better than 4K display. I recommend changing the default value to 2000 x 2000px, which is enough for most computer displays (in 2018) and it would mean better file size savings on the server. Those who need larger images can change the value manually.

**Comment by l3ku** [comment]
Related to this, the value 4000px X 4000px seems to be the current minimum for the limit: https://github.com/Seravo/seravo-plugin/blob/master/modules/optimize-images.php#L14-#L16. I think this was originally done to "fool-proof" the mechanism in such a way, that users would not completely ruin their images on accident. I think we should probably lower this value to 1000px X 1000px or such, and set a separate default value 2000px X 2000px.

**Comment by ottok** [comment]
Bug mentioned by @l3ku was fixed in commit 4ef368badbe0382bf0cd3256ba87422325b7cc67

I think it is safe to have a very high default limit. Then we can be pretty sure we don't upset anybody, not even some the most demanding graphic designer with 4K screens and retina displays.

**Comment by l3ku** [comment]
Is this issue still relevant? I also think that 4000px X 4000px is safe for a default size limit, and after the bugfix in 4ef368b this issue can be closed.

**Comment by l3ku** [comment]
Closing as the discussion in this issue has lead to a verdict that the default size should not be any smaller.
