### ISSUE TITLE
Consider showing "Tyhjennä välimuisti" button for editor user roles

### ISSUE THREAD

**Issue by runomarsista** [Seravo/seravo-plugin#82]
Consider showing "Tyhjennä välimuisti" button for editor user roles. At the moment it seems to be accessible only for administrators.

**Comment by ottok** [comment]
This has already been fixed in https://github.com/Seravo/seravo-plugin/commit/06d8703261a94a4f96c36c15d2177e184e26e0c5

**Comment by ottok** [comment]
Reopening this issue. It is questioned if the commit above actually works. This issue can be closed when it is proven that the commit above works.

**Comment by ottok** [comment]
Closed in https://github.com/Seravo/seravo-plugin/commit/2378e1577be5cbb27882aa0641e68e8373826f30
