### ISSUE TITLE
Cruft file scanner false positve: wp-tinymce.js.gz

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#84]
I noticed that the new cruft file scanner suggests to remove a file that is part of WP core. The cruft file scanning logic is too broad. It should be shallowed to not have false positives like this one.

![screenshot from 2018-01-18 10-06-07](https://user-images.githubusercontent.com/668724/35087060-8066ce00-fc37-11e7-9ef4-26fe8c15cf1e.png)

**Comment by simoke** [comment]
Fixed in 2f7eec92e7824429473788a0109c8f4d35c637f3
