### ISSUE TITLE
Cruft file UI issues: no results view, no backups claim

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#85]
Some cruft file UI considerations:
- Why does it claim that a removal cannot be undone? The UI should encourage customers to clean up cruft and not scare them away to not do it. And there are backups indeed and deletions can be undone within 30 days.
- If the cruft scanner does not find anything, it should say something like "Congratulations! You have no cruft around." and not just show a blank list.

![screenshot from 2018-01-18 10-09-02](https://user-images.githubusercontent.com/668724/35087247-39c5c658-fc38-11e7-87ac-2268ef045179.png)

**Comment by ottok** [comment]
Also noticed
- Finnish translations are missing (should only be updated after the UI is frozen)
- JS file has wrong syntax in use-strict
- there is a function `seravo_cruftfiles_status` that is never called from anywhere
- ajax calls don't return with standard `wp_json_encode` functions

**Comment by simoke** [comment]
Fixed in 2f7eec92e7824429473788a0109c8f4d35c637f3 and b6baf3626186b2655ff802de5f509066248c74d1
