### ISSUE TITLE
Remove Nyt käytössä: Production / Staging button from other than administrators and editors

### ISSUE THREAD

**Issue by runomarsista** [Seravo/seravo-plugin#87]
Remove "Nyt käytössä: Production / Staging" -button in wp-admin from other than administrators and editors

**Comment by ottok** [comment]
We need to update the hooks and filters in Seravo Plugin.

Scanned servers and found that only the following hooks/filters are actually used by at least one user:
* seravo_hide_update_data
* seravo_use_relative_urls (by far most popular with 16 users)

Everything else could be cleaned away and re-introduced only when somebody actually requests them, and then re-implemented in a way that solves an actual use-case.

**Comment by ottok** [comment]
Clean-up done in commit ec1e18e2de2e93d565d92f5c327c07af373d5c3d
