### ISSUE TITLE
Improved workflow for cruft files removal

### ISSUE THREAD

**Issue by karisavolainen** [Seravo/seravo-plugin#90]
Cruft files removal shows all files that it finds in such way that the user has to click the remove button individually for each file. It would be nice to have a 'select all' -button and individual files with a checkbox, so the user can deselect the files that they don't want to delete. 

![cruftfiles](https://user-images.githubusercontent.com/32452408/36152945-5eca5b42-10d5-11e8-94c5-cd77c640d357.png)

**Comment by tlxo** [comment]
Resolved with PR #138.
