### ISSUE TITLE
Suggest to site admin to remove inactive themes, inactive plugins and harmful plugins

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#93]
Many sites have all the twentysomething themes installed but don't use any of them. Many sites have half a dozen plugins installed that are not active. Many sites run query-monitor plugin and have the wp-content/db.php dropin for extended times on productions sites, and many sites run W3 Total Cache and other [plugins we recommend should be removed](https://wp-palvelu.fi/lisaosat/).

The cruft remover (or some other settings page) should list all unnecessary themes and plugins and suggest to remove them, with links to explanations why, and buttons to easily execute it.

**Comment by mikkoaf** [comment]
The remover should also take into account if their theme uses another theme as a template. We don't want the user to remove parent themes.

**Comment by l3ku** [comment]
As an update to this issue, the inactive and unwanted plugins functionality was introduced in https://github.com/Seravo/seravo-plugin/commit/bd18c09173f46e2b3a6b0b97b4cdc55e7141934e. However, inactive themes are yet not suggested for deletion.

**Comment by l3ku** [comment]
Implemented in 2a7edea and bd18c09.
