### ISSUE TITLE
Allow users to select primary domain

### ISSUE THREAD

**Issue by ottok** [Seravo/seravo-plugin#94]
On the Domains page, allow admin users to pick one domain as the primary one.

Based on that selection we could:
- update siteurl and home
- search-replace database to update old links
- extend the class Canonical_Domain_And_Https to always redirect visitors to the canonical domain

Note that the steps above are not always desired. There are good reasons why WordPress by default does not do any redirects or canonical domain assumptions. Design this with care.

**Comment by elguitar** [comment]
I assigned both @JoosuaKoskinen and me. Because of the complicated nature of this task, it is better that we work together and not rush into things.

**Comment by elguitar** [comment]
Steps which to implement in Seravo Plugin:
1. POST to API
1. Wait a second. Backend crunches search-replace
1. Run purge cache in the Seravo plugin

**Comment by JoosuaKoskinen** [comment]
This has been implemented in https://github.com/Seravo/seravo-plugin/pull/349 but might have some problems. Those are SWD related anyways so closing this.
