### ISSUE TITLE
Redesign plugin menu and page structure

### ISSUE THREAD

**Issue by l3ku** [Seravo/seravo-plugin#98]
Until now when we have added new features to Seravo Plugin, we have simply added a new page under "Tools". This has resulted in the menu becoming increasingly bloated with features, e.g.:

![screen shot 2018-05-16 at 14 57 56](https://user-images.githubusercontent.com/24781811/40115580-a1f4445a-5919-11e8-90af-de5c9029673a.png)

Before we continue to implement new features like the functionality described in #32, we should redesign the plugin menu structure by merging the content of different pages into similar categories, or even introducing an entirely new top-level WP admin menu page.

**Comment by simoke** [comment]
Also the upcoming GDPR features will be located under Tools menu, so relocating of Seravo plugin menu items makes sense.

**Comment by l3ku** [comment]
Note that if we choose to introduce a new WP admin menu page, we must also design a proper filter functionality: e.g. changing the name of the menu page or completely hiding it should be possible by adding filters to the site theme. This way, the site can also be branded with Seravo being merely the hosting provider (not showing up immediately in the customer's UI).

**Comment by elguitar** [comment]
Closing in favor of https://github.com/Seravo/seravo-plugin/issues/233
